<?php

namespace App\Domains\Sii\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SiiCatComunasSeeder extends Seeder
{
    public function run(): void
    {
        $comunas = [
            // ── Región de Tarapacá (01) ──────────────────────────────────────
            ['codigo' => '01101', 'nombre' => 'IQUIQUE',              'region_codigo' => '01', 'region_nombre' => 'REGIÓN DE TARAPACÁ',                                          'activo' => true],
            ['codigo' => '01107', 'nombre' => 'ALTO HOSPICIO',        'region_codigo' => '01', 'region_nombre' => 'REGIÓN DE TARAPACÁ',                                          'activo' => true],
            ['codigo' => '01401', 'nombre' => 'POZO ALMONTE',         'region_codigo' => '01', 'region_nombre' => 'REGIÓN DE TARAPACÁ',                                          'activo' => true],
            ['codigo' => '01402', 'nombre' => 'CAMIÑA',               'region_codigo' => '01', 'region_nombre' => 'REGIÓN DE TARAPACÁ',                                          'activo' => true],
            ['codigo' => '01403', 'nombre' => 'COLCHANE',             'region_codigo' => '01', 'region_nombre' => 'REGIÓN DE TARAPACÁ',                                          'activo' => true],
            ['codigo' => '01404', 'nombre' => 'HUARA',                'region_codigo' => '01', 'region_nombre' => 'REGIÓN DE TARAPACÁ',                                          'activo' => true],
            ['codigo' => '01405', 'nombre' => 'PICA',                 'region_codigo' => '01', 'region_nombre' => 'REGIÓN DE TARAPACÁ',                                          'activo' => true],

            // ── Región de Antofagasta (02) ───────────────────────────────────
            ['codigo' => '02101', 'nombre' => 'ANTOFAGASTA',          'region_codigo' => '02', 'region_nombre' => 'REGIÓN DE ANTOFAGASTA',                                       'activo' => true],
            ['codigo' => '02102', 'nombre' => 'MEJILLONES',           'region_codigo' => '02', 'region_nombre' => 'REGIÓN DE ANTOFAGASTA',                                       'activo' => true],
            ['codigo' => '02103', 'nombre' => 'SIERRA GORDA',         'region_codigo' => '02', 'region_nombre' => 'REGIÓN DE ANTOFAGASTA',                                       'activo' => true],
            ['codigo' => '02104', 'nombre' => 'TALTAL',               'region_codigo' => '02', 'region_nombre' => 'REGIÓN DE ANTOFAGASTA',                                       'activo' => true],
            ['codigo' => '02201', 'nombre' => 'CALAMA',               'region_codigo' => '02', 'region_nombre' => 'REGIÓN DE ANTOFAGASTA',                                       'activo' => true],
            ['codigo' => '02202', 'nombre' => 'OLLAGÜE',              'region_codigo' => '02', 'region_nombre' => 'REGIÓN DE ANTOFAGASTA',                                       'activo' => true],
            ['codigo' => '02203', 'nombre' => 'SAN PEDRO DE ATACAMA', 'region_codigo' => '02', 'region_nombre' => 'REGIÓN DE ANTOFAGASTA',                                       'activo' => true],
            ['codigo' => '02301', 'nombre' => 'TOCOPILLA',            'region_codigo' => '02', 'region_nombre' => 'REGIÓN DE ANTOFAGASTA',                                       'activo' => true],
            ['codigo' => '02302', 'nombre' => 'MARÍA ELENA',          'region_codigo' => '02', 'region_nombre' => 'REGIÓN DE ANTOFAGASTA',                                       'activo' => true],

            // ── Región de Atacama (03) ───────────────────────────────────────
            ['codigo' => '03101', 'nombre' => 'COPIAPÓ',              'region_codigo' => '03', 'region_nombre' => 'REGIÓN DE ATACAMA',                                           'activo' => true],
            ['codigo' => '03102', 'nombre' => 'CALDERA',              'region_codigo' => '03', 'region_nombre' => 'REGIÓN DE ATACAMA',                                           'activo' => true],
            ['codigo' => '03103', 'nombre' => 'TIERRA AMARILLA',      'region_codigo' => '03', 'region_nombre' => 'REGIÓN DE ATACAMA',                                           'activo' => true],
            ['codigo' => '03201', 'nombre' => 'CHAÑARAL',             'region_codigo' => '03', 'region_nombre' => 'REGIÓN DE ATACAMA',                                           'activo' => true],
            ['codigo' => '03202', 'nombre' => 'DIEGO DE ALMAGRO',     'region_codigo' => '03', 'region_nombre' => 'REGIÓN DE ATACAMA',                                           'activo' => true],
            ['codigo' => '03301', 'nombre' => 'VALLENAR',             'region_codigo' => '03', 'region_nombre' => 'REGIÓN DE ATACAMA',                                           'activo' => true],
            ['codigo' => '03302', 'nombre' => 'ALTO DEL CARMEN',      'region_codigo' => '03', 'region_nombre' => 'REGIÓN DE ATACAMA',                                           'activo' => true],
            ['codigo' => '03303', 'nombre' => 'FREIRINA',             'region_codigo' => '03', 'region_nombre' => 'REGIÓN DE ATACAMA',                                           'activo' => true],
            ['codigo' => '03304', 'nombre' => 'HUASCO',               'region_codigo' => '03', 'region_nombre' => 'REGIÓN DE ATACAMA',                                           'activo' => true],

            // ── Región de Coquimbo (04) ──────────────────────────────────────
            ['codigo' => '04101', 'nombre' => 'LA SERENA',            'region_codigo' => '04', 'region_nombre' => 'REGIÓN DE COQUIMBO',                                          'activo' => true],
            ['codigo' => '04102', 'nombre' => 'COQUIMBO',             'region_codigo' => '04', 'region_nombre' => 'REGIÓN DE COQUIMBO',                                          'activo' => true],
            ['codigo' => '04103', 'nombre' => 'ANDACOLLO',            'region_codigo' => '04', 'region_nombre' => 'REGIÓN DE COQUIMBO',                                          'activo' => true],
            ['codigo' => '04104', 'nombre' => 'LA HIGUERA',           'region_codigo' => '04', 'region_nombre' => 'REGIÓN DE COQUIMBO',                                          'activo' => true],
            ['codigo' => '04105', 'nombre' => 'PAIGUANO',             'region_codigo' => '04', 'region_nombre' => 'REGIÓN DE COQUIMBO',                                          'activo' => true],
            ['codigo' => '04106', 'nombre' => 'VICUÑA',               'region_codigo' => '04', 'region_nombre' => 'REGIÓN DE COQUIMBO',                                          'activo' => true],
            ['codigo' => '04201', 'nombre' => 'ILLAPEL',              'region_codigo' => '04', 'region_nombre' => 'REGIÓN DE COQUIMBO',                                          'activo' => true],
            ['codigo' => '04202', 'nombre' => 'CANELA',               'region_codigo' => '04', 'region_nombre' => 'REGIÓN DE COQUIMBO',                                          'activo' => true],
            ['codigo' => '04203', 'nombre' => 'LOS VILOS',            'region_codigo' => '04', 'region_nombre' => 'REGIÓN DE COQUIMBO',                                          'activo' => true],
            ['codigo' => '04204', 'nombre' => 'SALAMANCA',            'region_codigo' => '04', 'region_nombre' => 'REGIÓN DE COQUIMBO',                                          'activo' => true],
            ['codigo' => '04301', 'nombre' => 'OVALLE',               'region_codigo' => '04', 'region_nombre' => 'REGIÓN DE COQUIMBO',                                          'activo' => true],
            ['codigo' => '04302', 'nombre' => 'COMBARBALÁ',           'region_codigo' => '04', 'region_nombre' => 'REGIÓN DE COQUIMBO',                                          'activo' => true],
            ['codigo' => '04303', 'nombre' => 'MONTE PATRIA',         'region_codigo' => '04', 'region_nombre' => 'REGIÓN DE COQUIMBO',                                          'activo' => true],
            ['codigo' => '04304', 'nombre' => 'PUNITAQUI',            'region_codigo' => '04', 'region_nombre' => 'REGIÓN DE COQUIMBO',                                          'activo' => true],
            ['codigo' => '04305', 'nombre' => 'RÍO HURTADO',          'region_codigo' => '04', 'region_nombre' => 'REGIÓN DE COQUIMBO',                                          'activo' => true],

            // ── Región de Valparaíso (05) ────────────────────────────────────
            ['codigo' => '05101', 'nombre' => 'VALPARAÍSO',           'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05102', 'nombre' => 'CASABLANCA',           'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05103', 'nombre' => 'CONCÓN',               'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05104', 'nombre' => 'JUAN FERNÁNDEZ',       'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05105', 'nombre' => 'PUCHUNCAVÍ',           'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05107', 'nombre' => 'QUINTERO',             'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05109', 'nombre' => 'VIÑA DEL MAR',         'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05201', 'nombre' => 'ISLA DE PASCUA',       'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05301', 'nombre' => 'LOS ANDES',            'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05302', 'nombre' => 'CALLE LARGA',          'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
        ];

        DB::table('sii_cat_comunas')->insertOrIgnore($comunas);
        $comunas = [];

        $comunas = [
            ['codigo' => '05303', 'nombre' => 'RINCONADA',            'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05304', 'nombre' => 'SAN ESTEBAN',          'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05401', 'nombre' => 'LA LIGUA',             'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05402', 'nombre' => 'CABILDO',              'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05403', 'nombre' => 'PAPUDO',               'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05404', 'nombre' => 'PETORCA',              'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05405', 'nombre' => 'ZAPALLAR',             'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05501', 'nombre' => 'QUILLOTA',             'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05502', 'nombre' => 'CALERA',               'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05503', 'nombre' => 'HIJUELAS',             'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05504', 'nombre' => 'LA CRUZ',              'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05506', 'nombre' => 'NOGALES',              'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05601', 'nombre' => 'SAN ANTONIO',          'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05602', 'nombre' => 'ALGARROBO',            'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05603', 'nombre' => 'CARTAGENA',            'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05604', 'nombre' => 'EL QUISCO',            'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05605', 'nombre' => 'EL TABO',              'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05606', 'nombre' => 'SANTO DOMINGO',        'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05701', 'nombre' => 'SAN FELIPE',           'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05702', 'nombre' => 'CATEMU',               'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05703', 'nombre' => 'LLAY-LLAY',            'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05704', 'nombre' => 'PANQUEHUE',            'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05705', 'nombre' => 'PUTAENDO',             'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05706', 'nombre' => 'SANTA MARÍA',          'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05801', 'nombre' => 'QUILPUÉ',              'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05802', 'nombre' => 'LIMACHE',              'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05803', 'nombre' => 'OLMUÉ',                'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],
            ['codigo' => '05804', 'nombre' => 'VILLA ALEMANA',        'region_codigo' => '05', 'region_nombre' => 'REGIÓN DE VALPARAÍSO',                                        'activo' => true],

            // ── Región del Libertador General Bernardo O'Higgins (06) ────────
            ['codigo' => '06101', 'nombre' => 'RANCAGUA',             'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06102', 'nombre' => 'CODEGUA',              'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06103', 'nombre' => 'COINCO',               'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06104', 'nombre' => 'COLTAUCO',             'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06105', 'nombre' => 'DOÑIHUE',              'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06106', 'nombre' => 'GRANEROS',             'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06107', 'nombre' => 'LAS CABRAS',           'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06108', 'nombre' => 'MACHALÍ',              'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06109', 'nombre' => 'MALLOA',               'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06110', 'nombre' => 'MOSTAZAL',             'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06111', 'nombre' => 'OLIVAR',               'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06112', 'nombre' => 'PEUMO',                'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06113', 'nombre' => 'PICHIDEGUA',           'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06114', 'nombre' => 'QUINTA DE TILCOCO',    'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06115', 'nombre' => 'RENGO',                'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06116', 'nombre' => 'REQUÍNOA',             'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06117', 'nombre' => 'SAN VICENTE',          'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06201', 'nombre' => 'PICHILEMU',            'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06202', 'nombre' => 'LA ESTRELLA',          'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06203', 'nombre' => 'LITUECHE',             'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06204', 'nombre' => 'MARCHIGÜE',            'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
        ];

        DB::table('sii_cat_comunas')->insertOrIgnore($comunas);
        $comunas = [];

        $comunas = [
            ['codigo' => '06205', 'nombre' => 'NAVIDAD',              'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06206', 'nombre' => 'PAREDONES',            'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06301', 'nombre' => 'SAN FERNANDO',         'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06302', 'nombre' => 'CHÉPICA',              'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06303', 'nombre' => 'CHIMBARONGO',          'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06304', 'nombre' => 'LOLOL',                'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06305', 'nombre' => 'NANCAGUA',             'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06306', 'nombre' => 'PALMILLA',             'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06307', 'nombre' => 'PERALILLO',            'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06308', 'nombre' => 'PLACILLA',             'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06309', 'nombre' => 'PUMANQUE',             'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],
            ['codigo' => '06310', 'nombre' => 'SANTA CRUZ',           'region_codigo' => '06', 'region_nombre' => "REGIÓN DEL LIBERTADOR GENERAL BERNARDO O'HIGGINS",            'activo' => true],

            // ── Región del Maule (07) ────────────────────────────────────────
            ['codigo' => '07101', 'nombre' => 'TALCA',                'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07102', 'nombre' => 'CONSTITUCIÓN',         'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07103', 'nombre' => 'CUREPTO',              'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07104', 'nombre' => 'EMPEDRADO',            'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07105', 'nombre' => 'MAULE',                'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07106', 'nombre' => 'PELARCO',              'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07107', 'nombre' => 'PENCAHUE',             'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07108', 'nombre' => 'RÍO CLARO',            'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07109', 'nombre' => 'SAN CLEMENTE',         'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07110', 'nombre' => 'SAN RAFAEL',           'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07201', 'nombre' => 'CAUQUENES',            'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07202', 'nombre' => 'CHANCO',               'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07203', 'nombre' => 'PELLUHUE',             'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07301', 'nombre' => 'CURICÓ',               'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07302', 'nombre' => 'HUALAÑÉ',              'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07303', 'nombre' => 'LICANTÉN',             'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07304', 'nombre' => 'MOLINA',               'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07305', 'nombre' => 'RAUCO',                'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07306', 'nombre' => 'ROMERAL',              'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07307', 'nombre' => 'SAGRADA FAMILIA',      'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07308', 'nombre' => 'TENO',                 'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07309', 'nombre' => 'VICHUQUÉN',            'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07401', 'nombre' => 'LINARES',              'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07402', 'nombre' => 'COLBÚN',               'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07403', 'nombre' => 'LONGAVÍ',              'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07404', 'nombre' => 'PARRAL',               'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07405', 'nombre' => 'RETIRO',               'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07406', 'nombre' => 'SAN JAVIER',           'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07407', 'nombre' => 'VILLA ALEGRE',         'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],
            ['codigo' => '07408', 'nombre' => 'YERBAS BUENAS',        'region_codigo' => '07', 'region_nombre' => 'REGIÓN DEL MAULE',                                            'activo' => true],

            // ── Región del Biobío (08) ───────────────────────────────────────
            ['codigo' => '08101', 'nombre' => 'CONCEPCIÓN',           'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08102', 'nombre' => 'CORONEL',              'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08103', 'nombre' => 'CHIGUAYANTE',          'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08104', 'nombre' => 'FLORIDA',              'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08105', 'nombre' => 'HUALPÉN',              'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08106', 'nombre' => 'HUALQUI',              'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08107', 'nombre' => 'LOTA',                 'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08108', 'nombre' => 'PENCO',                'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08109', 'nombre' => 'SAN PEDRO DE LA PAZ',  'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08110', 'nombre' => 'SANTA JUANA',          'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
        ];

        DB::table('sii_cat_comunas')->insertOrIgnore($comunas);
        $comunas = [];

        $comunas = [
            ['codigo' => '08111', 'nombre' => 'TALCAHUANO',           'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08112', 'nombre' => 'TOMÉ',                 'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08201', 'nombre' => 'LEBU',                 'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08202', 'nombre' => 'ARAUCO',               'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08203', 'nombre' => 'CAÑETE',               'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08204', 'nombre' => 'CONTULMO',             'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08205', 'nombre' => 'CURANILAHUE',          'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08206', 'nombre' => 'LOS ÁLAMOS',           'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08207', 'nombre' => 'TIRÚA',                'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08301', 'nombre' => 'LOS ÁNGELES',          'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08302', 'nombre' => 'ANTUCO',               'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08303', 'nombre' => 'CABRERO',              'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08304', 'nombre' => 'LAJA',                 'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08305', 'nombre' => 'MULCHÉN',              'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08306', 'nombre' => 'NACIMIENTO',           'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08307', 'nombre' => 'NEGRETE',              'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08308', 'nombre' => 'QUILACO',              'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08309', 'nombre' => 'QUILLECO',             'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08310', 'nombre' => 'SAN ROSENDO',          'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08311', 'nombre' => 'SANTA BÁRBARA',        'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08312', 'nombre' => 'TUCAPEL',              'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08313', 'nombre' => 'YUMBEL',               'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            // Comunas históricas 08xxx que migraron a Ñuble — se conservan por compatibilidad SII
            ['codigo' => '08401', 'nombre' => 'CHILLÁN',              'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08402', 'nombre' => 'BULNES',               'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08403', 'nombre' => 'COBQUECURA',           'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08404', 'nombre' => 'COELEMU',              'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08405', 'nombre' => 'COIHUECO',             'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08406', 'nombre' => 'CHILLÁN VIEJO',        'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08407', 'nombre' => 'EL CARMEN',            'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08408', 'nombre' => 'NINHUE',               'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08409', 'nombre' => 'ÑIQUÉN',               'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08410', 'nombre' => 'PEMUCO',               'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08411', 'nombre' => 'PINTO',                'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08412', 'nombre' => 'PORTEZUELO',           'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08413', 'nombre' => 'QUILLÓN',              'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08414', 'nombre' => 'QUIRIHUE',             'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08415', 'nombre' => 'RÁNQUIL',              'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08416', 'nombre' => 'SAN CARLOS',           'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08417', 'nombre' => 'SAN FABIÁN',           'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08418', 'nombre' => 'SAN IGNACIO',          'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08419', 'nombre' => 'SAN NICOLÁS',          'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08420', 'nombre' => 'TREGUACO',             'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],
            ['codigo' => '08421', 'nombre' => 'YUNGAY',               'region_codigo' => '08', 'region_nombre' => 'REGIÓN DEL BIOBÍO',                                           'activo' => true],

            // ── Región de La Araucanía (09) ──────────────────────────────────
            ['codigo' => '09101', 'nombre' => 'TEMUCO',               'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09102', 'nombre' => 'CARAHUE',              'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09103', 'nombre' => 'CUNCO',                'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09104', 'nombre' => 'CURARREHUE',           'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09105', 'nombre' => 'FREIRE',               'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09106', 'nombre' => 'GALVARINO',            'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09107', 'nombre' => 'GORBEA',               'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09108', 'nombre' => 'LAUTARO',              'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
        ];

        DB::table('sii_cat_comunas')->insertOrIgnore($comunas);
        $comunas = [];

        $comunas = [
            ['codigo' => '09109', 'nombre' => 'LONCOCHE',             'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09110', 'nombre' => 'MELIPEUCO',            'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09111', 'nombre' => 'NUEVA IMPERIAL',       'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09112', 'nombre' => 'PADRE LAS CASAS',      'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09113', 'nombre' => 'PERQUENCO',            'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09114', 'nombre' => 'PITRUFQUÉN',           'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09115', 'nombre' => 'PUCÓN',                'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09116', 'nombre' => 'SAAVEDRA',             'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09117', 'nombre' => 'TEODORO SCHMIDT',      'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09118', 'nombre' => 'TOLTÉN',               'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09119', 'nombre' => 'VILCÚN',               'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09120', 'nombre' => 'VILLARRICA',           'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09121', 'nombre' => 'CHOLCHOL',             'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09201', 'nombre' => 'ANGOL',                'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09202', 'nombre' => 'COLLIPULLI',           'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09203', 'nombre' => 'CURACAUTÍN',           'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09204', 'nombre' => 'ERCILLA',              'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09205', 'nombre' => 'LONQUIMAY',            'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09206', 'nombre' => 'LOS SAUCES',           'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09207', 'nombre' => 'LUMACO',               'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09208', 'nombre' => 'PURÉN',                'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09209', 'nombre' => 'RENAICO',              'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09210', 'nombre' => 'TRAIGUÉN',             'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],
            ['codigo' => '09211', 'nombre' => 'VICTORIA',             'region_codigo' => '09', 'region_nombre' => 'REGIÓN DE LA ARAUCANÍA',                                      'activo' => true],

            // ── Región de Los Lagos (10) ─────────────────────────────────────
            ['codigo' => '10101', 'nombre' => 'PUERTO MONTT',         'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10102', 'nombre' => 'CALBUCO',              'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10103', 'nombre' => 'COCHAMÓ',              'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10104', 'nombre' => 'FRESIA',               'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10105', 'nombre' => 'FRUTILLAR',            'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10106', 'nombre' => 'LOS MUERMOS',          'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10107', 'nombre' => 'LLANQUIHUE',           'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10108', 'nombre' => 'MAULLÍN',              'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10109', 'nombre' => 'PUERTO VARAS',         'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10201', 'nombre' => 'CASTRO',               'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10202', 'nombre' => 'ANCUD',                'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10203', 'nombre' => 'CHONCHI',              'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10204', 'nombre' => 'CURACO DE VÉLEZ',      'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10205', 'nombre' => 'DALCAHUE',             'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10206', 'nombre' => 'PUQUELDÓN',            'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10207', 'nombre' => 'QUEILÉN',              'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10208', 'nombre' => 'QUELLÓN',              'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10209', 'nombre' => 'QUEMCHI',              'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10210', 'nombre' => 'QUINCHAO',             'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10301', 'nombre' => 'OSORNO',               'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10302', 'nombre' => 'PUERTO OCTAY',         'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10303', 'nombre' => 'PURRANQUE',            'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10304', 'nombre' => 'PUYEHUE',              'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10305', 'nombre' => 'RÍO NEGRO',            'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10306', 'nombre' => 'SAN JUAN DE LA COSTA', 'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10307', 'nombre' => 'SAN PABLO',            'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10401', 'nombre' => 'CHAITÉN',              'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10402', 'nombre' => 'FUTALEUFÚ',            'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10403', 'nombre' => 'HUALAIHUÉ',            'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
            ['codigo' => '10404', 'nombre' => 'PALENA',               'region_codigo' => '10', 'region_nombre' => 'REGIÓN DE LOS LAGOS',                                         'activo' => true],
        ];

        DB::table('sii_cat_comunas')->insertOrIgnore($comunas);
        $comunas = [];

        $comunas = [
            // ── Región Aysén del General Carlos Ibáñez del Campo (11) ────────
            ['codigo' => '11101', 'nombre' => 'COYHAIQUE',            'region_codigo' => '11', 'region_nombre' => 'REGIÓN AYSÉN DEL GENERAL CARLOS IBÁÑEZ DEL CAMPO',            'activo' => true],
            ['codigo' => '11102', 'nombre' => 'LAGO VERDE',           'region_codigo' => '11', 'region_nombre' => 'REGIÓN AYSÉN DEL GENERAL CARLOS IBÁÑEZ DEL CAMPO',            'activo' => true],
            ['codigo' => '11201', 'nombre' => 'AYSÉN',                'region_codigo' => '11', 'region_nombre' => 'REGIÓN AYSÉN DEL GENERAL CARLOS IBÁÑEZ DEL CAMPO',            'activo' => true],
            ['codigo' => '11202', 'nombre' => 'CISNES',               'region_codigo' => '11', 'region_nombre' => 'REGIÓN AYSÉN DEL GENERAL CARLOS IBÁÑEZ DEL CAMPO',            'activo' => true],
            ['codigo' => '11203', 'nombre' => 'GUAITECAS',            'region_codigo' => '11', 'region_nombre' => 'REGIÓN AYSÉN DEL GENERAL CARLOS IBÁÑEZ DEL CAMPO',            'activo' => true],
            ['codigo' => '11301', 'nombre' => 'COCHRANE',             'region_codigo' => '11', 'region_nombre' => 'REGIÓN AYSÉN DEL GENERAL CARLOS IBÁÑEZ DEL CAMPO',            'activo' => true],
            ['codigo' => '11302', 'nombre' => "O'HIGGINS",            'region_codigo' => '11', 'region_nombre' => 'REGIÓN AYSÉN DEL GENERAL CARLOS IBÁÑEZ DEL CAMPO',            'activo' => true],
            ['codigo' => '11303', 'nombre' => 'TORTEL',               'region_codigo' => '11', 'region_nombre' => 'REGIÓN AYSÉN DEL GENERAL CARLOS IBÁÑEZ DEL CAMPO',            'activo' => true],
            ['codigo' => '11401', 'nombre' => 'CHILE CHICO',          'region_codigo' => '11', 'region_nombre' => 'REGIÓN AYSÉN DEL GENERAL CARLOS IBÁÑEZ DEL CAMPO',            'activo' => true],
            ['codigo' => '11402', 'nombre' => 'RÍO IBÁÑEZ',          'region_codigo' => '11', 'region_nombre' => 'REGIÓN AYSÉN DEL GENERAL CARLOS IBÁÑEZ DEL CAMPO',            'activo' => true],

            // ── Región de Magallanes y de la Antártica Chilena (12) ──────────
            ['codigo' => '12101', 'nombre' => 'PUNTA ARENAS',         'region_codigo' => '12', 'region_nombre' => 'REGIÓN DE MAGALLANES Y DE LA ANTÁRTICA CHILENA',              'activo' => true],
            ['codigo' => '12102', 'nombre' => 'LAGUNA BLANCA',        'region_codigo' => '12', 'region_nombre' => 'REGIÓN DE MAGALLANES Y DE LA ANTÁRTICA CHILENA',              'activo' => true],
            ['codigo' => '12103', 'nombre' => 'RÍO VERDE',            'region_codigo' => '12', 'region_nombre' => 'REGIÓN DE MAGALLANES Y DE LA ANTÁRTICA CHILENA',              'activo' => true],
            ['codigo' => '12104', 'nombre' => 'SAN GREGORIO',         'region_codigo' => '12', 'region_nombre' => 'REGIÓN DE MAGALLANES Y DE LA ANTÁRTICA CHILENA',              'activo' => true],
            ['codigo' => '12201', 'nombre' => 'CABO DE HORNOS',       'region_codigo' => '12', 'region_nombre' => 'REGIÓN DE MAGALLANES Y DE LA ANTÁRTICA CHILENA',              'activo' => true],
            ['codigo' => '12202', 'nombre' => 'ANTÁRTICA',            'region_codigo' => '12', 'region_nombre' => 'REGIÓN DE MAGALLANES Y DE LA ANTÁRTICA CHILENA',              'activo' => true],
            ['codigo' => '12301', 'nombre' => 'PORVENIR',             'region_codigo' => '12', 'region_nombre' => 'REGIÓN DE MAGALLANES Y DE LA ANTÁRTICA CHILENA',              'activo' => true],
            ['codigo' => '12302', 'nombre' => 'PRIMAVERA',            'region_codigo' => '12', 'region_nombre' => 'REGIÓN DE MAGALLANES Y DE LA ANTÁRTICA CHILENA',              'activo' => true],
            ['codigo' => '12303', 'nombre' => 'TIMAUKEL',             'region_codigo' => '12', 'region_nombre' => 'REGIÓN DE MAGALLANES Y DE LA ANTÁRTICA CHILENA',              'activo' => true],
            ['codigo' => '12401', 'nombre' => 'NATALES',              'region_codigo' => '12', 'region_nombre' => 'REGIÓN DE MAGALLANES Y DE LA ANTÁRTICA CHILENA',              'activo' => true],
            ['codigo' => '12402', 'nombre' => 'TORRES DEL PAINE',     'region_codigo' => '12', 'region_nombre' => 'REGIÓN DE MAGALLANES Y DE LA ANTÁRTICA CHILENA',              'activo' => true],

            // ── Región Metropolitana de Santiago (13) ────────────────────────
            ['codigo' => '13101', 'nombre' => 'SANTIAGO',             'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13102', 'nombre' => 'CERRILLOS',            'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13103', 'nombre' => 'CERRO NAVIA',          'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13104', 'nombre' => 'CONCHALÍ',             'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13105', 'nombre' => 'EL BOSQUE',            'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13106', 'nombre' => 'ESTACIÓN CENTRAL',     'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13107', 'nombre' => 'HUECHURABA',           'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13108', 'nombre' => 'INDEPENDENCIA',        'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13109', 'nombre' => 'LA CISTERNA',          'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13110', 'nombre' => 'LA FLORIDA',           'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13111', 'nombre' => 'LA GRANJA',            'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13112', 'nombre' => 'LA PINTANA',           'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13113', 'nombre' => 'LA REINA',             'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13114', 'nombre' => 'LAS CONDES',           'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13115', 'nombre' => 'LO BARNECHEA',         'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13116', 'nombre' => 'LO ESPEJO',            'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13117', 'nombre' => 'LO PRADO',             'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13118', 'nombre' => 'MACUL',                'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13119', 'nombre' => 'MAIPÚ',                'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13120', 'nombre' => 'ÑUÑOA',                'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13121', 'nombre' => 'PEDRO AGUIRRE CERDA',  'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13122', 'nombre' => 'PEÑALOLÉN',            'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13123', 'nombre' => 'PROVIDENCIA',          'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13124', 'nombre' => 'PUDAHUEL',             'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13125', 'nombre' => 'QUILICURA',            'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13126', 'nombre' => 'QUINTA NORMAL',        'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13127', 'nombre' => 'RECOLETA',             'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13128', 'nombre' => 'RENCA',                'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
        ];

        DB::table('sii_cat_comunas')->insertOrIgnore($comunas);
        $comunas = [];

        $comunas = [
            ['codigo' => '13129', 'nombre' => 'SAN JOAQUÍN',          'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13130', 'nombre' => 'SAN MIGUEL',           'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13131', 'nombre' => 'SAN RAMÓN',            'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13132', 'nombre' => 'VITACURA',             'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13201', 'nombre' => 'PUENTE ALTO',          'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13202', 'nombre' => 'PIRQUE',               'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13203', 'nombre' => 'SAN JOSÉ DE MAIPO',    'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13301', 'nombre' => 'COLINA',               'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13302', 'nombre' => 'LAMPA',                'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13303', 'nombre' => 'TIL TIL',              'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13401', 'nombre' => 'SAN BERNARDO',         'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13402', 'nombre' => 'BUIN',                 'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13403', 'nombre' => 'CALERA DE TANGO',      'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13404', 'nombre' => 'PAINE',                'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13501', 'nombre' => 'MELIPILLA',            'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13502', 'nombre' => 'ALHUÉ',                'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13503', 'nombre' => 'CURACAVÍ',             'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13504', 'nombre' => 'MARÍA PINTO',          'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13505', 'nombre' => 'SAN PEDRO',            'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13601', 'nombre' => 'TALAGANTE',            'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13602', 'nombre' => 'EL MONTE',             'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13603', 'nombre' => 'ISLA DE MAIPO',        'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13604', 'nombre' => 'PADRE HURTADO',        'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],
            ['codigo' => '13605', 'nombre' => 'PEÑAFLOR',             'region_codigo' => '13', 'region_nombre' => 'REGIÓN METROPOLITANA DE SANTIAGO',                            'activo' => true],

            // ── Región de Los Ríos (14) ──────────────────────────────────────
            ['codigo' => '14101', 'nombre' => 'VALDIVIA',             'region_codigo' => '14', 'region_nombre' => 'REGIÓN DE LOS RÍOS',                                          'activo' => true],
            ['codigo' => '14102', 'nombre' => 'CORRAL',               'region_codigo' => '14', 'region_nombre' => 'REGIÓN DE LOS RÍOS',                                          'activo' => true],
            ['codigo' => '14103', 'nombre' => 'FUTRONO',              'region_codigo' => '14', 'region_nombre' => 'REGIÓN DE LOS RÍOS',                                          'activo' => true],
            ['codigo' => '14104', 'nombre' => 'LA UNIÓN',             'region_codigo' => '14', 'region_nombre' => 'REGIÓN DE LOS RÍOS',                                          'activo' => true],
            ['codigo' => '14105', 'nombre' => 'LAGO RANCO',           'region_codigo' => '14', 'region_nombre' => 'REGIÓN DE LOS RÍOS',                                          'activo' => true],
            ['codigo' => '14106', 'nombre' => 'LANCO',                'region_codigo' => '14', 'region_nombre' => 'REGIÓN DE LOS RÍOS',                                          'activo' => true],
            ['codigo' => '14107', 'nombre' => 'LOS LAGOS',            'region_codigo' => '14', 'region_nombre' => 'REGIÓN DE LOS RÍOS',                                          'activo' => true],
            ['codigo' => '14108', 'nombre' => 'MÁFIL',                'region_codigo' => '14', 'region_nombre' => 'REGIÓN DE LOS RÍOS',                                          'activo' => true],
            ['codigo' => '14109', 'nombre' => 'MARIQUINA',            'region_codigo' => '14', 'region_nombre' => 'REGIÓN DE LOS RÍOS',                                          'activo' => true],
            ['codigo' => '14110', 'nombre' => 'PAILLACO',             'region_codigo' => '14', 'region_nombre' => 'REGIÓN DE LOS RÍOS',                                          'activo' => true],
            ['codigo' => '14111', 'nombre' => 'PANGUIPULLI',          'region_codigo' => '14', 'region_nombre' => 'REGIÓN DE LOS RÍOS',                                          'activo' => true],
            ['codigo' => '14112', 'nombre' => 'RÍO BUENO',            'region_codigo' => '14', 'region_nombre' => 'REGIÓN DE LOS RÍOS',                                          'activo' => true],

            // ── Región de Arica y Parinacota (15) ───────────────────────────
            ['codigo' => '15101', 'nombre' => 'ARICA',                'region_codigo' => '15', 'region_nombre' => 'REGIÓN DE ARICA Y PARINACOTA',                                'activo' => true],
            ['codigo' => '15102', 'nombre' => 'CAMARONES',            'region_codigo' => '15', 'region_nombre' => 'REGIÓN DE ARICA Y PARINACOTA',                                'activo' => true],
            ['codigo' => '15201', 'nombre' => 'PUTRE',                'region_codigo' => '15', 'region_nombre' => 'REGIÓN DE ARICA Y PARINACOTA',                                'activo' => true],
            ['codigo' => '15202', 'nombre' => 'GENERAL LAGOS',        'region_codigo' => '15', 'region_nombre' => 'REGIÓN DE ARICA Y PARINACOTA',                                'activo' => true],

            // ── Región de Ñuble (16) ─────────────────────────────────────────
            ['codigo' => '16101', 'nombre' => 'CHILLÁN',              'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
            ['codigo' => '16102', 'nombre' => 'BULNES',               'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
            ['codigo' => '16103', 'nombre' => 'CHILLÁN VIEJO',        'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
            ['codigo' => '16104', 'nombre' => 'EL CARMEN',            'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
            ['codigo' => '16105', 'nombre' => 'PEMUCO',               'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
            ['codigo' => '16106', 'nombre' => 'PINTO',                'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
            ['codigo' => '16107', 'nombre' => 'QUILLÓN',              'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
            ['codigo' => '16108', 'nombre' => 'SAN IGNACIO',          'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
            ['codigo' => '16109', 'nombre' => 'YUNGAY',               'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
            ['codigo' => '16201', 'nombre' => 'QUIRIHUE',             'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
            ['codigo' => '16202', 'nombre' => 'COBQUECURA',           'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
            ['codigo' => '16203', 'nombre' => 'COELEMU',              'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
            ['codigo' => '16204', 'nombre' => 'NINHUE',               'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
            ['codigo' => '16205', 'nombre' => 'PORTEZUELO',           'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
            ['codigo' => '16206', 'nombre' => 'RÁNQUIL',              'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
            ['codigo' => '16207', 'nombre' => 'TREGUACO',             'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
            ['codigo' => '16301', 'nombre' => 'SAN CARLOS',           'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
            ['codigo' => '16302', 'nombre' => 'COIHUECO',             'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
            ['codigo' => '16303', 'nombre' => 'ÑIQUÉN',               'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
            ['codigo' => '16304', 'nombre' => 'SAN FABIÁN',           'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
            ['codigo' => '16305', 'nombre' => 'SAN NICOLÁS',          'region_codigo' => '16', 'region_nombre' => 'REGIÓN DE ÑUBLE',                                             'activo' => true],
        ];

        DB::table('sii_cat_comunas')->insertOrIgnore($comunas);
    }
}
