<?php

namespace App\Domains\Sii\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SiiCatActecoSeeder extends Seeder
{
    public function run(): void
    {
        $actividades = [

            // SECCIÓN A — AGRICULTURA, GANADERÍA, SILVICULTURA Y PESCA
            ['codigo' => 1110,  'nombre' => 'CULTIVO DE CEREALES (EXC. ARROZ), LEGUMBRES Y SEMILLAS OLEAGINOSAS',                          'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1120,  'nombre' => 'CULTIVO DE ARROZ',                                                                             'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1130,  'nombre' => 'CULTIVO DE HORTALIZAS Y MELONES Y RAÍCES Y TUBÉRCULOS',                                       'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1140,  'nombre' => 'CULTIVO DE CAÑA DE AZÚCAR',                                                                   'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1150,  'nombre' => 'CULTIVO DE TABACO',                                                                            'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1160,  'nombre' => 'CULTIVO DE PLANTAS DE FIBRA',                                                                  'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1190,  'nombre' => 'CULTIVO DE OTRAS PLANTAS NO PERENNES',                                                         'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1210,  'nombre' => 'CULTIVO DE LA VID',                                                                            'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1220,  'nombre' => 'CULTIVO DE FRUTAS TROPICALES Y SUBTROPICALES',                                                 'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1230,  'nombre' => 'CULTIVO DE CÍTRICOS',                                                                         'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1240,  'nombre' => 'CULTIVO DE FRUTAS DE PEPITA Y DE HUESO',                                                      'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1250,  'nombre' => 'CULTIVO DE OTROS FRUTOS Y NUECES DE ÁRBOLES Y ARBUSTOS',                                      'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1260,  'nombre' => 'CULTIVO DE FRUTOS OLEAGINOSOS',                                                               'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1270,  'nombre' => 'CULTIVO DE PLANTAS CON LAS QUE SE PREPARAN BEBIDAS',                                          'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1280,  'nombre' => 'CULTIVO DE ESPECIAS Y PLANTAS AROMÁTICAS Y MEDICINALES',                                      'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1290,  'nombre' => 'CULTIVO DE OTRAS PLANTAS PERENNES',                                                           'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1300,  'nombre' => 'PROPAGACIÓN DE PLANTAS',                                                                      'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1410,  'nombre' => 'CRÍA DE GANADO BOVINO Y BÚFALOS',                                                             'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1420,  'nombre' => 'CRÍA DE CABALLOS Y OTROS ÉQUIDOS',                                                            'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1430,  'nombre' => 'CRÍA DE CAMELLOS Y CAMÉLIDOS',                                                                'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1440,  'nombre' => 'CRÍA DE OVEJAS Y CABRAS',                                                                     'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1450,  'nombre' => 'CRÍA DE CERDOS',                                                                              'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1460,  'nombre' => 'CRÍA DE AVES DE CORRAL',                                                                      'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1490,  'nombre' => 'CRÍA DE OTROS ANIMALES',                                                                      'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1500,  'nombre' => 'CULTIVO DE PRODUCTOS AGRÍCOLAS EN COMBINACIÓN CON LA CRÍA DE ANIMALES',                       'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1610,  'nombre' => 'ACTIVIDADES DE APOYO A LA AGRICULTURA',                                                       'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1620,  'nombre' => 'ACTIVIDADES DE APOYO A LA GANADERÍA',                                                         'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1630,  'nombre' => 'ACTIVIDADES POSCOSECHA',                                                                      'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1640,  'nombre' => 'TRATAMIENTO DE SEMILLAS',                                                                     'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 1700,  'nombre' => 'CAZA ORDINARIA Y MEDIANTE TRAMPAS',                                                           'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 2100,  'nombre' => 'SILVICULTURA Y OTRAS ACTIVIDADES FORESTALES',                                                  'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 2200,  'nombre' => 'EXTRACCIÓN DE MADERA',                                                                        'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 2300,  'nombre' => 'RECOLECCIÓN DE PRODUCTOS FORESTALES NO MADEREROS',                                            'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 2400,  'nombre' => 'SERVICIOS DE APOYO A LA SILVICULTURA',                                                        'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 3110,  'nombre' => 'PESCA MARÍTIMA',                                                                              'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 3120,  'nombre' => 'PESCA EN AGUA DULCE',                                                                         'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 3210,  'nombre' => 'ACUICULTURA MARÍTIMA',                                                                        'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 3220,  'nombre' => 'ACUICULTURA EN AGUA DULCE',                                                                   'categoria' => 'A', 'afecto_iva' => true,  'activo' => true],

            // SECCIÓN B — EXPLOTACIÓN DE MINAS Y CANTERAS
            ['codigo' => 5100,  'nombre' => 'EXTRACCIÓN DE CARBÓN DE PIEDRA',                                                              'categoria' => 'B', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 6100,  'nombre' => 'EXTRACCIÓN DE PETRÓLEO CRUDO',                                                                'categoria' => 'B', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 6200,  'nombre' => 'EXTRACCIÓN DE GAS NATURAL',                                                                   'categoria' => 'B', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 7100,  'nombre' => 'EXTRACCIÓN DE MINERALES DE HIERRO',                                                           'categoria' => 'B', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 7210,  'nombre' => 'EXTRACCIÓN DE MINERALES DE URANIO Y TORIO',                                                   'categoria' => 'B', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 7290,  'nombre' => 'EXTRACCIÓN DE OTROS MINERALES METALÍFEROS NO FERROSOS',                                       'categoria' => 'B', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 8100,  'nombre' => 'EXTRACCIÓN DE PIEDRA, ARENA Y ARCILLA',                                                       'categoria' => 'B', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 8910,  'nombre' => 'EXTRACCIÓN DE MINERALES PARA FABRICACIÓN DE ABONOS Y PRODUCTOS QUÍMICOS',                     'categoria' => 'B', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 8920,  'nombre' => 'EXTRACCIÓN DE TURBA',                                                                         'categoria' => 'B', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 8930,  'nombre' => 'EXTRACCIÓN DE SAL',                                                                           'categoria' => 'B', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 8990,  'nombre' => 'EXTRACCIÓN DE OTRAS MINAS Y CANTERAS N.C.P.',                                                 'categoria' => 'B', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 9100,  'nombre' => 'ACTIVIDADES DE APOYO PARA LA EXTRACCIÓN DE PETRÓLEO Y GAS NATURAL',                           'categoria' => 'B', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 9900,  'nombre' => 'ACTIVIDADES DE APOYO PARA OTRAS ACTIVIDADES DE EXTRACCIÓN DE MINAS Y CANTERAS',               'categoria' => 'B', 'afecto_iva' => true,  'activo' => true],

            // SECCIÓN C — INDUSTRIAS MANUFACTURERAS
            ['codigo' => 10100, 'nombre' => 'ELABORACIÓN Y CONSERVACIÓN DE CARNE',                                                         'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 10200, 'nombre' => 'ELABORACIÓN Y CONSERVACIÓN DE PESCADO, CRUSTÁCEOS Y MOLUSCOS',                                'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 10300, 'nombre' => 'ELABORACIÓN Y CONSERVACIÓN DE FRUTAS, LEGUMBRES Y HORTALIZAS',                                'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 10400, 'nombre' => 'ELABORACIÓN DE ACEITES Y GRASAS DE ORIGEN VEGETAL Y ANIMAL',                                  'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 10500, 'nombre' => 'ELABORACIÓN DE PRODUCTOS LÁCTEOS',                                                            'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 10610, 'nombre' => 'ELABORACIÓN DE PRODUCTOS DE MOLINERÍA',                                                       'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 10620, 'nombre' => 'ELABORACIÓN DE ALMIDONES Y PRODUCTOS DERIVADOS DEL ALMIDÓN',                                  'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 10710, 'nombre' => 'ELABORACIÓN DE PAN Y PRODUCTOS FRESCOS DE PANADERÍA Y PASTELERÍA',                            'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 10720, 'nombre' => 'ELABORACIÓN DE GALLETAS Y OTROS PRODUCTOS DE PANADERÍA',                                      'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 10730, 'nombre' => 'ELABORACIÓN DE MACARRONES, FIDEOS Y PRODUCTOS FARINÁCEOS SIMILARES',                          'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 10740, 'nombre' => 'ELABORACIÓN DE MACARRONES, FIDEOS Y PRODUCTOS FARINÁCEOS SIMILARES NCP',                      'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 10750, 'nombre' => 'ELABORACIÓN DE PLATOS Y COMIDAS PREPARADOS',                                                  'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 10790, 'nombre' => 'ELABORACIÓN DE OTROS PRODUCTOS ALIMENTICIOS N.C.P.',                                          'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 10800, 'nombre' => 'ELABORACIÓN DE ALIMENTOS PREPARADOS PARA ANIMALES',                                           'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 11010, 'nombre' => 'DESTILACIÓN, RECTIFICACIÓN Y MEZCLA DE BEBIDAS ALCOHÓLICAS',                                  'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 11020, 'nombre' => 'ELABORACIÓN DE VINOS',                                                                        'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 11030, 'nombre' => 'ELABORACIÓN DE BEBIDAS MALTEADAS Y DE MALTA',                                                 'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 11040, 'nombre' => 'ELABORACIÓN DE BEBIDAS NO ALCOHÓLICAS',                                                       'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 12000, 'nombre' => 'ELABORACIÓN DE PRODUCTOS DE TABACO',                                                          'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 13100, 'nombre' => 'PREPARACIÓN E HILADURA DE FIBRAS TEXTILES',                                                   'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 13200, 'nombre' => 'TEJEDURA DE PRODUCTOS TEXTILES',                                                              'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 13300, 'nombre' => 'ACABADO DE PRODUCTOS TEXTILES',                                                               'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 13910, 'nombre' => 'FABRICACIÓN DE TEJIDOS DE PUNTO Y GANCHILLO',                                                 'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 13920, 'nombre' => 'FABRICACIÓN DE ARTÍCULOS CONFECCIONADOS DE MATERIALES TEXTILES, EXCEPTO PRENDAS DE VESTIR',   'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 13930, 'nombre' => 'FABRICACIÓN DE TAPICES Y ALFOMBRAS',                                                          'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 13940, 'nombre' => 'FABRICACIÓN DE CUERDAS, CORDELES, BRAMANTES Y REDES',                                         'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 13990, 'nombre' => 'FABRICACIÓN DE OTROS PRODUCTOS TEXTILES N.C.P.',                                              'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 14100, 'nombre' => 'FABRICACIÓN DE PRENDAS DE VESTIR, EXCEPTO PRENDAS DE PIEL',                                   'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 14200, 'nombre' => 'FABRICACIÓN DE ARTÍCULOS DE PIEL',                                                            'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 14300, 'nombre' => 'FABRICACIÓN DE ARTÍCULOS DE PUNTO Y GANCHILLO',                                               'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 15110, 'nombre' => 'CURTIDO Y ADOBO DE CUEROS',                                                                   'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 15120, 'nombre' => 'FABRICACIÓN DE MALETAS, BOLSOS DE MANO Y ARTÍCULOS SIMILARES',                                'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 15200, 'nombre' => 'FABRICACIÓN DE CALZADO',                                                                      'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 16100, 'nombre' => 'ASERRADO Y ACEPILLADURA DE MADERA',                                                           'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 16210, 'nombre' => 'FABRICACIÓN DE HOJAS DE MADERA PARA ENCHAPADO Y TABLEROS',                                    'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 16220, 'nombre' => 'FABRICACIÓN DE PARQUET Y PISOS DE MADERA',                                                    'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 16230, 'nombre' => 'FABRICACIÓN DE OTRAS HOJAS DE MADERA Y PANELES',                                              'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 16240, 'nombre' => 'FABRICACIÓN DE RECIPIENTES DE MADERA',                                                        'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 16290, 'nombre' => 'FABRICACIÓN DE OTROS PRODUCTOS DE MADERA',                                                    'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 17110, 'nombre' => 'FABRICACIÓN DE PASTA DE MADERA, PAPEL Y CARTÓN',                                              'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 17120, 'nombre' => 'FABRICACIÓN DE PAPEL Y CARTÓN ONDULADO Y ENVASES DE PAPEL Y CARTÓN',                          'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 17190, 'nombre' => 'FABRICACIÓN DE OTROS ARTÍCULOS DE PAPEL Y CARTÓN',                                            'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 17210, 'nombre' => 'FABRICACIÓN DE CAJAS Y BOLSAS DE PAPEL Y CARTÓN',                                             'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 17220, 'nombre' => 'FABRICACIÓN DE ARTÍCULOS DE PAPEL Y CARTÓN DE USO DOMÉSTICO E HIGIÉNICO-SANITARIO',           'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 17230, 'nombre' => 'FABRICACIÓN DE ARTÍCULOS DE PAPELERÍA',                                                       'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 17240, 'nombre' => 'FABRICACIÓN DE PAPEL PINTADO',                                                                'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 17290, 'nombre' => 'FABRICACIÓN DE OTROS ARTÍCULOS DE PAPEL Y CARTÓN N.C.P.',                                     'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 18110, 'nombre' => 'IMPRESIÓN',                                                                                   'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 18120, 'nombre' => 'ACTIVIDADES DE SERVICIOS RELACIONADOS CON LA IMPRESIÓN',                                      'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 18200, 'nombre' => 'REPRODUCCIÓN DE GRABACIONES',                                                                 'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 19100, 'nombre' => 'FABRICACIÓN DE PRODUCTOS DE HORNOS DE COQUE',                                                 'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 19200, 'nombre' => 'FABRICACIÓN DE PRODUCTOS DE LA REFINACIÓN DEL PETRÓLEO',                                      'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 20110, 'nombre' => 'FABRICACIÓN DE GASES INDUSTRIALES',                                                           'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 20120, 'nombre' => 'FABRICACIÓN DE COLORANTES Y PIGMENTOS',                                                       'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 20130, 'nombre' => 'FABRICACIÓN DE OTROS PRODUCTOS QUÍMICOS INORGÁNICOS BÁSICOS',                                 'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 20140, 'nombre' => 'FABRICACIÓN DE OTROS PRODUCTOS QUÍMICOS ORGÁNICOS BÁSICOS',                                   'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 20150, 'nombre' => 'FABRICACIÓN DE ABONOS Y COMPUESTOS DE NITRÓGENO',                                             'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 20160, 'nombre' => 'FABRICACIÓN DE PLÁSTICOS EN FORMAS PRIMARIAS',                                                'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 20170, 'nombre' => 'FABRICACIÓN DE CAUCHO SINTÉTICO EN FORMAS PRIMARIAS',                                         'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 20200, 'nombre' => 'FABRICACIÓN DE PLAGUICIDAS Y OTROS PRODUCTOS AGROQUÍMICOS',                                   'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 20300, 'nombre' => 'FABRICACIÓN DE PINTURAS, BARNICES Y PRODUCTOS DE REVESTIMIENTO SIMILARES',                    'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 20410, 'nombre' => 'FABRICACIÓN DE JABONES Y DETERGENTES',                                                        'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 20420, 'nombre' => 'FABRICACIÓN DE PERFUMES Y PREPARADOS DE TOCADOR',                                             'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 20510, 'nombre' => 'FABRICACIÓN DE EXPLOSIVOS',                                                                   'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 20520, 'nombre' => 'FABRICACIÓN DE COLAS',                                                                        'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 20530, 'nombre' => 'FABRICACIÓN DE ACEITES ESENCIALES',                                                           'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 20590, 'nombre' => 'FABRICACIÓN DE OTROS PRODUCTOS QUÍMICOS N.C.P.',                                              'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 20600, 'nombre' => 'FABRICACIÓN DE FIBRAS ARTIFICIALES',                                                          'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 21100, 'nombre' => 'FABRICACIÓN DE PRODUCTOS FARMACÉUTICOS BÁSICOS',                                              'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 21200, 'nombre' => 'FABRICACIÓN DE MEDICAMENTOS Y OTROS PRODUCTOS FARMACÉUTICOS',                                 'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 22110, 'nombre' => 'FABRICACIÓN DE CUBIERTAS Y CÁMARAS DE CAUCHO',                                                'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 22190, 'nombre' => 'FABRICACIÓN DE OTROS PRODUCTOS DE CAUCHO',                                                    'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 22210, 'nombre' => 'FABRICACIÓN DE PLACAS, HOJAS, TUBOS Y PERFILES DE PLÁSTICO',                                  'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 22220, 'nombre' => 'FABRICACIÓN DE ENVASES DE PLÁSTICO',                                                          'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 22230, 'nombre' => 'FABRICACIÓN DE ARTÍCULOS DE PLÁSTICO PARA LA CONSTRUCCIÓN',                                   'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 22290, 'nombre' => 'FABRICACIÓN DE OTROS PRODUCTOS DE PLÁSTICO',                                                  'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 23110, 'nombre' => 'FABRICACIÓN DE VIDRIO PLANO',                                                                 'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 23120, 'nombre' => 'FABRICACIÓN DE VIDRIO HUECO',                                                                 'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 23130, 'nombre' => 'FABRICACIÓN DE FIBRAS DE VIDRIO',                                                             'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 23190, 'nombre' => 'FABRICACIÓN Y ELABORACIÓN DE OTROS ARTÍCULOS DE VIDRIO',                                      'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 23200, 'nombre' => 'FABRICACIÓN DE PRODUCTOS REFRACTARIOS',                                                       'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 23310, 'nombre' => 'FABRICACIÓN DE AZULEJOS Y BALDOSAS DE CERÁMICA Y PORCELANA',                                  'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 23320, 'nombre' => 'FABRICACIÓN DE LADRILLOS, TEJAS Y PRODUCTOS DE ARCILLA PARA CONSTRUCCIÓN',                    'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 23390, 'nombre' => 'FABRICACIÓN DE OTROS PRODUCTOS DE CERÁMICA Y PORCELANA',                                      'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 23410, 'nombre' => 'FABRICACIÓN DE ARTÍCULOS DOMÉSTICOS Y ORNAMENTALES DE CERÁMICA Y PORCELANA',                  'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 23490, 'nombre' => 'FABRICACIÓN DE OTROS PRODUCTOS DE CERÁMICA Y PORCELANA N.C.P.',                               'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 23510, 'nombre' => 'FABRICACIÓN DE CEMENTO, CAL Y YESO',                                                          'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 23520, 'nombre' => 'FABRICACIÓN DE ARTÍCULOS DE HORMIGÓN, CEMENTO Y YESO',                                        'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 23610, 'nombre' => 'FABRICACIÓN DE ARTÍCULOS DE HORMIGÓN PARA LA CONSTRUCCIÓN',                                   'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 23620, 'nombre' => 'FABRICACIÓN DE ARTÍCULOS DE YESO PARA LA CONSTRUCCIÓN',                                       'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 23630, 'nombre' => 'FABRICACIÓN DE HORMIGÓN PREMEZCLADO',                                                         'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 23640, 'nombre' => 'FABRICACIÓN DE MORTERO',                                                                      'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 23650, 'nombre' => 'FABRICACIÓN DE FIBROCEMENTO',                                                                 'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 23690, 'nombre' => 'FABRICACIÓN DE OTROS ARTÍCULOS DE HORMIGÓN, CEMENTO Y YESO',                                  'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 23700, 'nombre' => 'CORTE, TALLA Y ACABADO DE LA PIEDRA',                                                         'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 23900, 'nombre' => 'FABRICACIÓN DE OTROS PRODUCTOS MINERALES NO METÁLICOS N.C.P.',                                'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 24100, 'nombre' => 'INDUSTRIAS BÁSICAS DE HIERRO Y ACERO',                                                        'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 24200, 'nombre' => 'FABRICACIÓN DE PRODUCTOS PRIMARIOS DE METALES PRECIOSOS Y METALES NO FERROSOS',               'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 24310, 'nombre' => 'FUNDICIÓN DE HIERRO Y ACERO',                                                                 'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 24320, 'nombre' => 'FUNDICIÓN DE METALES NO FERROSOS',                                                            'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 25110, 'nombre' => 'FABRICACIÓN DE ESTRUCTURAS METÁLICAS Y SUS PARTES',                                           'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 25120, 'nombre' => 'FABRICACIÓN DE PUERTAS Y VENTANAS DE METAL',                                                  'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 25130, 'nombre' => 'FABRICACIÓN DE GENERADORES DE VAPOR',                                                         'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 25200, 'nombre' => 'FABRICACIÓN DE ARMAS Y MUNICIONES',                                                           'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 25910, 'nombre' => 'FABRICACIÓN DE TAMBORES, DEPÓSITOS Y RECIPIENTES DE METAL',                                   'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 25920, 'nombre' => 'FABRICACIÓN DE ENVASES METÁLICOS LIGEROS',                                                    'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 25930, 'nombre' => 'FABRICACIÓN DE ARTÍCULOS DE ALAMBRE, CADENAS Y MUELLES',                                      'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 25940, 'nombre' => 'FABRICACIÓN DE PERNOS, TUERCAS, TORNILLOS Y ARTÍCULOS SIMILARES',                             'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 25990, 'nombre' => 'FABRICACIÓN DE OTROS PRODUCTOS ELABORADOS DE METAL N.C.P.',                                   'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 26100, 'nombre' => 'FABRICACIÓN DE COMPONENTES Y TABLEROS ELECTRÓNICOS',                                          'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 26200, 'nombre' => 'FABRICACIÓN DE COMPUTADORES Y EQUIPO PERIFÉRICO',                                             'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 26300, 'nombre' => 'FABRICACIÓN DE EQUIPO DE COMUNICACIONES',                                                     'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 26400, 'nombre' => 'FABRICACIÓN DE APARATOS ELECTRÓNICOS DE CONSUMO',                                             'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 26510, 'nombre' => 'FABRICACIÓN DE INSTRUMENTOS Y APARATOS PARA MEDIR',                                           'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 26520, 'nombre' => 'FABRICACIÓN DE RELOJES',                                                                      'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 26600, 'nombre' => 'FABRICACIÓN DE EQUIPO DE IRRADIACIÓN',                                                        'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 26700, 'nombre' => 'FABRICACIÓN DE INSTRUMENTOS ÓPTICOS Y EQUIPO FOTOGRÁFICO',                                    'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 26800, 'nombre' => 'FABRICACIÓN DE SOPORTES MAGNÉTICOS Y ÓPTICOS',                                                'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 27100, 'nombre' => 'FABRICACIÓN DE MOTORES, GENERADORES Y TRANSFORMADORES ELÉCTRICOS',                            'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 27200, 'nombre' => 'FABRICACIÓN DE PILAS Y ACUMULADORES ELÉCTRICOS',                                              'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 27310, 'nombre' => 'FABRICACIÓN DE CABLES DE FIBRA ÓPTICA',                                                       'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 27320, 'nombre' => 'FABRICACIÓN DE OTROS HILOS Y CABLES ELÉCTRICOS Y ELECTRÓNICOS',                               'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 27330, 'nombre' => 'FABRICACIÓN DE DISPOSITIVOS DE CABLEADO',                                                     'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 27400, 'nombre' => 'FABRICACIÓN DE EQUIPO ELÉCTRICO DE ILUMINACIÓN',                                              'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 27500, 'nombre' => 'FABRICACIÓN DE APARATOS DE USO DOMÉSTICO',                                                    'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 27900, 'nombre' => 'FABRICACIÓN DE OTROS TIPOS DE EQUIPO ELÉCTRICO',                                              'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 28110, 'nombre' => 'FABRICACIÓN DE MOTORES Y TURBINAS',                                                           'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 28120, 'nombre' => 'FABRICACIÓN DE EQUIPO DE PROPULSIÓN DE FLUIDOS',                                              'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 28130, 'nombre' => 'FABRICACIÓN DE OTRAS BOMBAS, COMPRESORES, GRIFOS Y VÁLVULAS',                                 'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 28140, 'nombre' => 'FABRICACIÓN DE COJINETES, ENGRANAJES, TRENES DE ENGRANAJES Y PIEZAS DE TRANSMISIÓN',          'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 28150, 'nombre' => 'FABRICACIÓN DE HORNOS, HOGARES Y QUEMADORES',                                                 'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 28160, 'nombre' => 'FABRICACIÓN DE EQUIPO DE ELEVACIÓN Y MANIPULACIÓN',                                           'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 28170, 'nombre' => 'FABRICACIÓN DE MAQUINARIA Y EQUIPO DE OFICINA (EXCEPTO COMPUTADORES Y EQUIPO PERIFÉRICO)',    'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 28180, 'nombre' => 'FABRICACIÓN DE HERRAMIENTAS MANUALES CON MOTOR',                                              'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 28190, 'nombre' => 'FABRICACIÓN DE OTROS TIPOS DE MAQUINARIA DE USO GENERAL',                                     'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 28210, 'nombre' => 'FABRICACIÓN DE MAQUINARIA AGROPECUARIA Y FORESTAL',                                           'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 28220, 'nombre' => 'FABRICACIÓN DE MÁQUINAS FORMADORAS DE METAL Y DE MÁQUINAS HERRAMIENTA',                       'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 28230, 'nombre' => 'FABRICACIÓN DE MAQUINARIA METALÚRGICA',                                                       'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 28240, 'nombre' => 'FABRICACIÓN DE MAQUINARIA PARA EXPLOTACIÓN DE MINAS Y CANTERAS Y PARA OBRAS DE CONSTRUCCIÓN', 'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 28250, 'nombre' => 'FABRICACIÓN DE MAQUINARIA PARA LA ELABORACIÓN DE ALIMENTOS, BEBIDAS Y TABACO',                'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 28260, 'nombre' => 'FABRICACIÓN DE MAQUINARIA PARA LA ELABORACIÓN DE TEXTILES, PRENDAS DE VESTIR Y CUEROS',       'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 28290, 'nombre' => 'FABRICACIÓN DE OTROS TIPOS DE MAQUINARIA DE USO ESPECIAL',                                    'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 29100, 'nombre' => 'FABRICACIÓN DE VEHÍCULOS AUTOMOTORES',                                                        'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 29200, 'nombre' => 'FABRICACIÓN DE CARROCERÍAS PARA VEHÍCULOS AUTOMOTORES',                                       'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 29300, 'nombre' => 'FABRICACIÓN DE PARTES, PIEZAS Y ACCESORIOS PARA VEHÍCULOS AUTOMOTORES',                       'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 30110, 'nombre' => 'CONSTRUCCIÓN DE BUQUES Y ESTRUCTURAS FLOTANTES',                                              'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 30120, 'nombre' => 'CONSTRUCCIÓN DE EMBARCACIONES DE RECREO Y DEPORTE',                                           'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 30200, 'nombre' => 'FABRICACIÓN DE LOCOMOTORAS Y DE MATERIAL RODANTE',                                            'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 30300, 'nombre' => 'FABRICACIÓN DE AERONAVES, NAVES ESPACIALES Y MAQUINARIA CONEXA',                              'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 30400, 'nombre' => 'FABRICACIÓN DE VEHÍCULOS MILITARES DE COMBATE',                                               'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 30910, 'nombre' => 'FABRICACIÓN DE MOTOCICLETAS',                                                                 'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 30920, 'nombre' => 'FABRICACIÓN DE BICICLETAS Y DE SILLAS DE RUEDAS PARA PERSONAS CON DISCAPACIDAD',              'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 30990, 'nombre' => 'FABRICACIÓN DE OTROS TIPOS DE EQUIPO DE TRANSPORTE N.C.P.',                                   'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 31001, 'nombre' => 'FABRICACIÓN DE MUEBLES',                                                                      'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 32110, 'nombre' => 'FABRICACIÓN DE JOYAS Y ARTÍCULOS CONEXOS',                                                    'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 32120, 'nombre' => 'FABRICACIÓN DE BISUTERÍA Y ARTÍCULOS CONEXOS',                                                'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 32200, 'nombre' => 'FABRICACIÓN DE INSTRUMENTOS MUSICALES',                                                       'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 32300, 'nombre' => 'FABRICACIÓN DE ARTÍCULOS DE DEPORTE',                                                         'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 32400, 'nombre' => 'FABRICACIÓN DE JUEGOS Y JUGUETES',                                                            'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 32500, 'nombre' => 'FABRICACIÓN DE INSTRUMENTOS Y MATERIALES MÉDICOS Y ODONTOLÓGICOS',                            'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 32910, 'nombre' => 'FABRICACIÓN DE ESCOBAS, CEPILLOS Y ARTÍCULOS SIMILARES',                                      'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 32990, 'nombre' => 'OTRAS INDUSTRIAS MANUFACTURERAS N.C.P.',                                                      'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 33110, 'nombre' => 'REPARACIÓN DE PRODUCTOS ELABORADOS DE METAL',                                                 'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 33120, 'nombre' => 'REPARACIÓN DE MAQUINARIA',                                                                    'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 33130, 'nombre' => 'REPARACIÓN DE EQUIPO ELECTRÓNICO Y ÓPTICO',                                                   'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 33140, 'nombre' => 'REPARACIÓN DE EQUIPO ELÉCTRICO',                                                              'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 33150, 'nombre' => 'REPARACIÓN Y MANTENIMIENTO DE BUQUES Y EMBARCACIONES',                                        'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 33160, 'nombre' => 'REPARACIÓN Y MANTENIMIENTO DE AERONAVES Y NAVES ESPACIALES',                                  'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 33170, 'nombre' => 'REPARACIÓN Y MANTENIMIENTO DE OTRO EQUIPO DE TRANSPORTE',                                     'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 33190, 'nombre' => 'REPARACIÓN DE OTROS TIPOS DE EQUIPO',                                                         'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 33200, 'nombre' => 'INSTALACIÓN DE MAQUINARIA Y EQUIPO INDUSTRIALES',                                             'categoria' => 'C', 'afecto_iva' => true,  'activo' => true],

            // SECCIÓN D — SUMINISTRO DE ELECTRICIDAD, GAS, VAPOR Y AIRE ACONDICIONADO
            ['codigo' => 35100, 'nombre' => 'GENERACIÓN, TRANSMISIÓN Y DISTRIBUCIÓN DE ENERGÍA ELÉCTRICA',                                 'categoria' => 'D', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 35200, 'nombre' => 'FABRICACIÓN DE GAS Y DISTRIBUCIÓN DE COMBUSTIBLES GASEOSOS POR TUBERÍAS',                     'categoria' => 'D', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 35300, 'nombre' => 'SUMINISTRO DE VAPOR Y DE AIRE ACONDICIONADO',                                                 'categoria' => 'D', 'afecto_iva' => true,  'activo' => true],

            // SECCIÓN E — SUMINISTRO DE AGUA; EVACUACIÓN DE AGUAS RESIDUALES, GESTIÓN DE DESECHOS
            ['codigo' => 36000, 'nombre' => 'CAPTACIÓN, TRATAMIENTO Y DISTRIBUCIÓN DE AGUA',                                               'categoria' => 'E', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 37000, 'nombre' => 'EVACUACIÓN DE AGUAS RESIDUALES',                                                              'categoria' => 'E', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 38110, 'nombre' => 'RECOGIDA DE DESECHOS NO PELIGROSOS',                                                          'categoria' => 'E', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 38120, 'nombre' => 'RECOGIDA DE DESECHOS PELIGROSOS',                                                             'categoria' => 'E', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 38210, 'nombre' => 'TRATAMIENTO Y ELIMINACIÓN DE DESECHOS NO PELIGROSOS',                                         'categoria' => 'E', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 38220, 'nombre' => 'TRATAMIENTO Y ELIMINACIÓN DE DESECHOS PELIGROSOS',                                            'categoria' => 'E', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 38300, 'nombre' => 'RECUPERACIÓN DE MATERIALES',                                                                  'categoria' => 'E', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 39000, 'nombre' => 'ACTIVIDADES DE DESCONTAMINACIÓN Y OTROS SERVICIOS DE GESTIÓN DE DESECHOS',                    'categoria' => 'E', 'afecto_iva' => true,  'activo' => true],

            // SECCIÓN F — CONSTRUCCIÓN
            ['codigo' => 41001, 'nombre' => 'CONSTRUCCIÓN DE EDIFICIOS RESIDENCIALES',                                                     'categoria' => 'F', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 41002, 'nombre' => 'CONSTRUCCIÓN DE EDIFICIOS NO RESIDENCIALES',                                                  'categoria' => 'F', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 42100, 'nombre' => 'CONSTRUCCIÓN DE CARRETERAS Y LÍNEAS DE FERROCARRIL',                                          'categoria' => 'F', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 42200, 'nombre' => 'CONSTRUCCIÓN DE PROYECTOS DE SERVICIO PÚBLICO',                                               'categoria' => 'F', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 42900, 'nombre' => 'CONSTRUCCIÓN DE OTRAS OBRAS DE INGENIERÍA CIVIL',                                             'categoria' => 'F', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 43110, 'nombre' => 'DEMOLICIÓN',                                                                                  'categoria' => 'F', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 43120, 'nombre' => 'PREPARACIÓN DEL TERRENO',                                                                     'categoria' => 'F', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 43130, 'nombre' => 'PERFORACIÓN Y SONDEO',                                                                        'categoria' => 'F', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 43210, 'nombre' => 'INSTALACIONES ELÉCTRICAS',                                                                    'categoria' => 'F', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 43220, 'nombre' => 'INSTALACIONES DE FONTANERÍA, CALEFACCIÓN Y AIRE ACONDICIONADO',                               'categoria' => 'F', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 43290, 'nombre' => 'OTRAS INSTALACIONES PARA OBRAS DE CONSTRUCCIÓN',                                              'categoria' => 'F', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 43300, 'nombre' => 'TERMINACIÓN Y ACABADO DE EDIFICIOS',                                                          'categoria' => 'F', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 43900, 'nombre' => 'OTRAS ACTIVIDADES ESPECIALIZADAS DE CONSTRUCCIÓN',                                            'categoria' => 'F', 'afecto_iva' => true,  'activo' => true],

            // SECCIÓN G — COMERCIO AL POR MAYOR Y AL POR MENOR
            ['codigo' => 45110, 'nombre' => 'VENTA DE AUTOMÓVILES Y VEHÍCULOS AUTOMOTORES LIVIANOS',                                       'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 45120, 'nombre' => 'VENTA DE OTROS TIPOS DE VEHÍCULOS AUTOMOTORES',                                               'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 45200, 'nombre' => 'MANTENIMIENTO Y REPARACIÓN DE VEHÍCULOS AUTOMOTORES',                                         'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 45310, 'nombre' => 'VENTA AL POR MAYOR DE PARTES, PIEZAS Y ACCESORIOS PARA VEHÍCULOS AUTOMOTORES',                'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 45320, 'nombre' => 'VENTA AL POR MENOR DE PARTES, PIEZAS Y ACCESORIOS PARA VEHÍCULOS AUTOMOTORES',                'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 45401, 'nombre' => 'VENTA DE MOTOCICLETAS',                                                                       'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 45402, 'nombre' => 'MANTENIMIENTO Y REPARACIÓN DE MOTOCICLETAS',                                                  'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 45403, 'nombre' => 'VENTA AL POR MENOR DE COMBUSTIBLES',                                                          'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 46100, 'nombre' => 'VENTA AL POR MAYOR A CAMBIO DE UNA RETRIBUCIÓN O POR CONTRATA',                               'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 46110, 'nombre' => 'AGENTES DEDICADOS A LA VENTA DE MATERIAS PRIMAS AGROPECUARIAS',                               'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 46120, 'nombre' => 'AGENTES DEDICADOS A LA VENTA DE COMBUSTIBLES',                                                'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 46130, 'nombre' => 'AGENTES DEDICADOS A LA VENTA DE MADERA Y MATERIALES DE CONSTRUCCIÓN',                         'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 46140, 'nombre' => 'AGENTES DEDICADOS A LA VENTA DE MAQUINARIA',                                                  'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 46150, 'nombre' => 'AGENTES DEDICADOS A LA VENTA DE MUEBLES',                                                     'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 46160, 'nombre' => 'AGENTES DEDICADOS A LA VENTA DE PRODUCTOS TEXTILES, PRENDAS DE VESTIR Y CALZADO',             'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 46170, 'nombre' => 'AGENTES DEDICADOS A LA VENTA DE PRODUCTOS ALIMENTICIOS, BEBIDAS Y TABACO',                    'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 46180, 'nombre' => 'AGENTES DEDICADOS A LA VENTA DE OTROS PRODUCTOS ESPECÍFICOS',                                 'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 46190, 'nombre' => 'AGENTES DEDICADOS A LA VENTA DE PRODUCTOS VARIADOS',                                          'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 46200, 'nombre' => 'VENTA AL POR MAYOR DE MATERIAS PRIMAS AGROPECUARIAS',                                         'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 46300, 'nombre' => 'VENTA AL POR MAYOR DE ALIMENTOS, BEBIDAS Y TABACO',                                           'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 46400, 'nombre' => 'VENTA AL POR MAYOR DE ENSERES DOMÉSTICOS',                                                    'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 46500, 'nombre' => 'VENTA AL POR MAYOR DE MAQUINARIA, EQUIPO Y MATERIALES',                                       'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 46600, 'nombre' => 'VENTA AL POR MAYOR DE OTROS PRODUCTOS',                                                       'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 46900, 'nombre' => 'VENTA AL POR MAYOR NO ESPECIALIZADA',                                                         'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47110, 'nombre' => 'VENTA AL POR MENOR EN COMERCIOS NO ESPECIALIZADOS CON PREDOMINIO DE ALIMENTOS, BEBIDAS Y TABACO', 'categoria' => 'G', 'afecto_iva' => true, 'activo' => true],
            ['codigo' => 47190, 'nombre' => 'OTRAS ACTIVIDADES DE VENTA AL POR MENOR EN COMERCIOS NO ESPECIALIZADOS',                      'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47210, 'nombre' => 'VENTA AL POR MENOR DE FRUTAS Y HORTALIZAS',                                                   'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47220, 'nombre' => 'VENTA AL POR MENOR DE CARNE Y PRODUCTOS CÁRNICOS',                                            'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47230, 'nombre' => 'VENTA AL POR MENOR DE PESCADO, CRUSTÁCEOS Y MOLUSCOS',                                        'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47240, 'nombre' => 'VENTA AL POR MENOR DE PAN Y PRODUCTOS DE PANADERÍA, CONFITERÍA',                              'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47250, 'nombre' => 'VENTA AL POR MENOR DE BEBIDAS EN COMERCIOS ESPECIALIZADOS',                                   'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47260, 'nombre' => 'VENTA AL POR MENOR DE PRODUCTOS DE TABACO EN COMERCIOS ESPECIALIZADOS',                       'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47290, 'nombre' => 'OTRAS ACTIVIDADES DE VENTA AL POR MENOR DE PRODUCTOS ALIMENTICIOS EN COMERCIOS ESPECIALIZADOS', 'categoria' => 'G', 'afecto_iva' => true, 'activo' => true],
            ['codigo' => 47300, 'nombre' => 'VENTA AL POR MENOR DE COMBUSTIBLE PARA VEHÍCULOS AUTOMOTORES',                                'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47410, 'nombre' => 'VENTA AL POR MENOR DE COMPUTADORES, EQUIPO PERIFÉRICO Y PROGRAMAS INFORMÁTICOS',              'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47420, 'nombre' => 'VENTA AL POR MENOR DE EQUIPO DE SONIDO Y DE VÍDEO',                                           'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47510, 'nombre' => 'VENTA AL POR MENOR DE PRODUCTOS TEXTILES',                                                    'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47520, 'nombre' => 'VENTA AL POR MENOR DE ARTÍCULOS DE FERRETERÍA Y PINTURAS',                                    'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47530, 'nombre' => 'VENTA AL POR MENOR DE TAPICES, ALFOMBRAS Y CUBRIMIENTOS PARA PAREDES Y PISOS',                'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47540, 'nombre' => 'VENTA AL POR MENOR DE APARATOS ELÉCTRICOS DE USO DOMÉSTICO',                                  'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47590, 'nombre' => 'VENTA AL POR MENOR DE MUEBLES, EQUIPO DE ILUMINACIÓN Y OTROS ARTÍCULOS PARA EL HOGAR',        'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47610, 'nombre' => 'VENTA AL POR MENOR DE LIBROS, PERIÓDICOS Y ARTÍCULOS DE PAPELERÍA',                           'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47620, 'nombre' => 'VENTA AL POR MENOR DE GRABACIONES DE MÚSICA Y DE VÍDEO',                                      'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47630, 'nombre' => 'VENTA AL POR MENOR DE ARTÍCULOS DE DEPORTE',                                                  'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47640, 'nombre' => 'VENTA AL POR MENOR DE JUEGOS Y JUGUETES',                                                     'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47710, 'nombre' => 'VENTA AL POR MENOR DE PRENDAS DE VESTIR',                                                     'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47720, 'nombre' => 'VENTA AL POR MENOR DE CALZADO Y ARTÍCULOS DE CUERO',                                          'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47730, 'nombre' => 'VENTA AL POR MENOR DE PRODUCTOS FARMACÉUTICOS Y MÉDICOS',                                     'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47740, 'nombre' => 'VENTA AL POR MENOR DE ARTÍCULOS MÉDICOS Y ORTOPÉDICOS',                                       'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47750, 'nombre' => 'VENTA AL POR MENOR DE PRODUCTOS COSMÉTICOS Y DE TOCADOR',                                     'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47810, 'nombre' => 'VENTA AL POR MENOR DE ALIMENTOS, BEBIDAS Y TABACO EN PUESTOS',                                'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47820, 'nombre' => 'VENTA AL POR MENOR DE ARTÍCULOS TEXTILES, PRENDAS DE VESTIR Y CALZADO EN PUESTOS',            'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47890, 'nombre' => 'VENTA AL POR MENOR DE OTROS PRODUCTOS EN PUESTOS Y MERCADOS',                                 'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47910, 'nombre' => 'VENTA AL POR MENOR POR CORREO Y POR INTERNET',                                                'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 47990, 'nombre' => 'OTRAS ACTIVIDADES DE VENTA AL POR MENOR NO REALIZADAS EN COMERCIOS',                          'categoria' => 'G', 'afecto_iva' => true,  'activo' => true],

            // SECCIÓN H — TRANSPORTE Y ALMACENAMIENTO
            ['codigo' => 49100, 'nombre' => 'TRANSPORTE POR FERROCARRIL INTERURBANO',                                                      'categoria' => 'H', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 49200, 'nombre' => 'TRANSPORTE DE CARGA POR FERROCARRIL',                                                         'categoria' => 'H', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 49310, 'nombre' => 'TRANSPORTE URBANO Y SUBURBANO DE PASAJEROS POR VÍA TERRESTRE',                                'categoria' => 'H', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 49320, 'nombre' => 'TRANSPORTE DE PASAJEROS EN TAXIS',                                                            'categoria' => 'H', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 49390, 'nombre' => 'OTROS TIPOS DE TRANSPORTE TERRESTRE DE PASAJEROS N.C.P.',                                     'categoria' => 'H', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 49410, 'nombre' => 'TRANSPORTE DE CARGA POR CARRETERA',                                                           'categoria' => 'H', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 49420, 'nombre' => 'SERVICIOS DE MUDANZA',                                                                        'categoria' => 'H', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 49500, 'nombre' => 'TRANSPORTE POR TUBERÍAS',                                                                     'categoria' => 'H', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 50100, 'nombre' => 'TRANSPORTE MARÍTIMO Y DE CABOTAJE',                                                           'categoria' => 'H', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 50200, 'nombre' => 'TRANSPORTE FLUVIAL',                                                                          'categoria' => 'H', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 51100, 'nombre' => 'TRANSPORTE AÉREO DE PASAJEROS',                                                               'categoria' => 'H', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 51200, 'nombre' => 'TRANSPORTE AÉREO DE CARGA',                                                                   'categoria' => 'H', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 52100, 'nombre' => 'ALMACENAMIENTO Y DEPÓSITO',                                                                   'categoria' => 'H', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 52210, 'nombre' => 'ACTIVIDADES DE SERVICIOS VINCULADAS AL TRANSPORTE TERRESTRE',                                  'categoria' => 'H', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 52220, 'nombre' => 'ACTIVIDADES DE SERVICIOS VINCULADAS AL TRANSPORTE ACUÁTICO',                                  'categoria' => 'H', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 52230, 'nombre' => 'ACTIVIDADES DE SERVICIOS VINCULADAS AL TRANSPORTE AÉREO',                                     'categoria' => 'H', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 52240, 'nombre' => 'MANIPULACIÓN DE CARGA',                                                                       'categoria' => 'H', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 52290, 'nombre' => 'OTRAS ACTIVIDADES DE APOYO AL TRANSPORTE',                                                    'categoria' => 'H', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 53100, 'nombre' => 'ACTIVIDADES POSTALES',                                                                        'categoria' => 'H', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 53200, 'nombre' => 'ACTIVIDADES DE MENSAJERÍA',                                                                   'categoria' => 'H', 'afecto_iva' => true,  'activo' => true],

            // SECCIÓN I — ALOJAMIENTO Y SERVICIOS DE COMIDA
            ['codigo' => 55100, 'nombre' => 'ACTIVIDADES DE HOTELES Y ALOJAMIENTOS SIMILARES',                                             'categoria' => 'I', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 55200, 'nombre' => 'ACTIVIDADES DE CAMPING Y PARQUES PARA CASAS RODANTES Y REMOLQUES',                            'categoria' => 'I', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 55900, 'nombre' => 'OTRAS ACTIVIDADES DE ALOJAMIENTO',                                                            'categoria' => 'I', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 56100, 'nombre' => 'ACTIVIDADES DE RESTAURANTES Y DE SERVICIO MÓVIL DE COMIDAS',                                  'categoria' => 'I', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 56210, 'nombre' => 'SUMINISTRO DE COMIDAS POR ENCARGO',                                                           'categoria' => 'I', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 56290, 'nombre' => 'OTRAS ACTIVIDADES DE SERVICIO DE COMIDAS',                                                    'categoria' => 'I', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 56300, 'nombre' => 'ELABORACIÓN Y SERVICIO DE BEBIDAS',                                                           'categoria' => 'I', 'afecto_iva' => true,  'activo' => true],

            // SECCIÓN J — INFORMACIÓN Y COMUNICACIONES
            ['codigo' => 58110, 'nombre' => 'EDICIÓN DE LIBROS',                                                                           'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 58120, 'nombre' => 'EDICIÓN DE DIRECTORIOS Y LISTAS DE CORREO',                                                   'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 58130, 'nombre' => 'EDICIÓN DE PERIÓDICOS',                                                                       'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 58140, 'nombre' => 'EDICIÓN DE REVISTAS Y OTRAS PUBLICACIONES PERIÓDICAS',                                        'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 58190, 'nombre' => 'OTRAS ACTIVIDADES DE EDICIÓN',                                                                'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 58200, 'nombre' => 'EDICIÓN DE PROGRAMAS DE INFORMÁTICA',                                                         'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 59110, 'nombre' => 'PRODUCCIÓN DE PELÍCULAS CINEMATOGRÁFICAS, VÍDEOS Y PROGRAMAS DE TELEVISIÓN',                  'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 59120, 'nombre' => 'ACTIVIDADES DE POSPRODUCCIÓN DE PELÍCULAS CINEMATOGRÁFICAS, VÍDEOS Y PROGRAMAS DE TELEVISIÓN', 'categoria' => 'J', 'afecto_iva' => true, 'activo' => true],
            ['codigo' => 59130, 'nombre' => 'DISTRIBUCIÓN DE PELÍCULAS CINEMATOGRÁFICAS, VÍDEOS Y PROGRAMAS DE TELEVISIÓN',                'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 59140, 'nombre' => 'EXHIBICIÓN DE PELÍCULAS CINEMATOGRÁFICAS Y VÍDEOS',                                           'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 59200, 'nombre' => 'ACTIVIDADES DE GRABACIÓN DE SONIDO Y EDICIÓN DE MÚSICA',                                      'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 60100, 'nombre' => 'TRANSMISIONES DE RADIO',                                                                      'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 60200, 'nombre' => 'PROGRAMACIÓN Y TRANSMISIONES DE TELEVISIÓN',                                                  'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 61100, 'nombre' => 'ACTIVIDADES DE TELECOMUNICACIONES ALÁMBRICAS',                                                'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 61200, 'nombre' => 'ACTIVIDADES DE TELECOMUNICACIONES INALÁMBRICAS',                                              'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 61300, 'nombre' => 'ACTIVIDADES DE TELECOMUNICACIONES POR SATÉLITE',                                              'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 61900, 'nombre' => 'OTRAS ACTIVIDADES DE TELECOMUNICACIONES',                                                     'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 62010, 'nombre' => 'ACTIVIDADES DE DESARROLLO DE SISTEMAS INFORMÁTICOS (PLANIFICACIÓN, ANÁLISIS, DISEÑO, PROGRAMACIÓN, PRUEBAS)', 'categoria' => 'J', 'afecto_iva' => true, 'activo' => true],
            ['codigo' => 62020, 'nombre' => 'ACTIVIDADES DE CONSULTORÍA INFORMÁTICA Y GESTIÓN DE INSTALACIONES INFORMÁTICAS',              'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 62090, 'nombre' => 'OTRAS ACTIVIDADES DE TECNOLOGÍA DE LA INFORMACIÓN Y DE INFORMÁTICA',                          'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 63110, 'nombre' => 'PROCESAMIENTO DE DATOS, HOSPEDAJE Y ACTIVIDADES CONEXAS',                                     'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 63120, 'nombre' => 'PORTALES WEB',                                                                                'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 63910, 'nombre' => 'ACTIVIDADES DE AGENCIAS DE NOTICIAS',                                                         'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 63990, 'nombre' => 'OTRAS ACTIVIDADES DE SERVICIOS DE INFORMACIÓN N.C.P.',                                        'categoria' => 'J', 'afecto_iva' => true,  'activo' => true],

            // SECCIÓN K — ACTIVIDADES FINANCIERAS Y DE SEGUROS
            ['codigo' => 64110, 'nombre' => 'BANCA CENTRAL',                                                                               'categoria' => 'K', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 64190, 'nombre' => 'OTROS TIPOS DE INTERMEDIACIÓN MONETARIA',                                                     'categoria' => 'K', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 64200, 'nombre' => 'ACTIVIDADES DE SOCIEDADES DE CARTERA',                                                        'categoria' => 'K', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 64300, 'nombre' => 'FONDOS Y SOCIEDADES DE INVERSIÓN Y ENTIDADES FINANCIERAS SIMILARES',                          'categoria' => 'K', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 64910, 'nombre' => 'ARRENDAMIENTO FINANCIERO',                                                                    'categoria' => 'K', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 64920, 'nombre' => 'OTROS TIPOS DE CONCESIÓN DE CRÉDITO',                                                        'categoria' => 'K', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 64990, 'nombre' => 'OTRAS ACTIVIDADES DE SERVICIOS FINANCIEROS, EXCEPTO LAS DE SEGUROS Y FONDOS DE PENSIONES N.C.P.', 'categoria' => 'K', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 65100, 'nombre' => 'SEGUROS',                                                                                     'categoria' => 'K', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 65200, 'nombre' => 'REASEGUROS',                                                                                  'categoria' => 'K', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 65300, 'nombre' => 'FONDOS DE PENSIONES',                                                                         'categoria' => 'K', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 66110, 'nombre' => 'ADMINISTRACIÓN DE MERCADOS FINANCIEROS',                                                      'categoria' => 'K', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 66120, 'nombre' => 'ACTIVIDADES DE INTERMEDIACIÓN EN OPERACIONES CON VALORES Y MERCANCÍAS',                       'categoria' => 'K', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 66190, 'nombre' => 'OTRAS ACTIVIDADES AUXILIARES DE LAS ACTIVIDADES DE SERVICIOS FINANCIEROS',                    'categoria' => 'K', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 66210, 'nombre' => 'EVALUACIÓN DE RIESGOS Y DAÑOS',                                                               'categoria' => 'K', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 66220, 'nombre' => 'ACTIVIDADES DE AGENTES Y CORREDORES DE SEGUROS',                                              'categoria' => 'K', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 66290, 'nombre' => 'OTRAS ACTIVIDADES AUXILIARES DE LAS ACTIVIDADES DE SEGUROS Y FONDOS DE PENSIONES',            'categoria' => 'K', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 66300, 'nombre' => 'ACTIVIDADES DE GESTIÓN DE FONDOS',                                                            'categoria' => 'K', 'afecto_iva' => true,  'activo' => true],

            // SECCIÓN L — ACTIVIDADES INMOBILIARIAS
            ['codigo' => 68100, 'nombre' => 'ACTIVIDADES INMOBILIARIAS REALIZADAS CON BIENES PROPIOS O ARRENDADOS',                        'categoria' => 'L', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 68200, 'nombre' => 'ACTIVIDADES INMOBILIARIAS REALIZADAS A CAMBIO DE UNA RETRIBUCIÓN O POR CONTRATA',             'categoria' => 'L', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 68209, 'nombre' => 'OTRAS ACTIVIDADES INMOBILIARIAS REALIZADAS A CAMBIO DE UNA RETRIBUCIÓN O POR CONTRATA',       'categoria' => 'L', 'afecto_iva' => true,  'activo' => true],

            // SECCIÓN M — ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS
            ['codigo' => 69100, 'nombre' => 'ACTIVIDADES JURÍDICAS',                                                                       'categoria' => 'M', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 69200, 'nombre' => 'ACTIVIDADES DE CONTABILIDAD, TENEDURÍA DE LIBROS Y AUDITORÍA',                                'categoria' => 'M', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 70100, 'nombre' => 'ACTIVIDADES DE ADMINISTRACIÓN EMPRESARIAL',                                                   'categoria' => 'M', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 70200, 'nombre' => 'ACTIVIDADES DE CONSULTORÍA DE GESTIÓN EMPRESARIAL',                                           'categoria' => 'M', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 71100, 'nombre' => 'ACTIVIDADES DE ARQUITECTURA E INGENIERÍA Y ACTIVIDADES CONEXAS DE CONSULTORÍA TÉCNICA',       'categoria' => 'M', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 71200, 'nombre' => 'ENSAYOS Y ANÁLISIS TÉCNICOS',                                                                 'categoria' => 'M', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 72100, 'nombre' => 'INVESTIGACIÓN Y DESARROLLO EXPERIMENTAL EN EL CAMPO DE LAS CIENCIAS NATURALES',               'categoria' => 'M', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 72200, 'nombre' => 'INVESTIGACIÓN Y DESARROLLO EXPERIMENTAL EN EL CAMPO DE LAS CIENCIAS SOCIALES Y LAS HUMANIDADES', 'categoria' => 'M', 'afecto_iva' => true, 'activo' => true],
            ['codigo' => 73100, 'nombre' => 'PUBLICIDAD',                                                                                  'categoria' => 'M', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 73200, 'nombre' => 'ESTUDIOS DE MERCADO Y ENCUESTAS DE OPINIÓN PÚBLICA',                                          'categoria' => 'M', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 74100, 'nombre' => 'ACTIVIDADES ESPECIALIZADAS DE DISEÑO',                                                        'categoria' => 'M', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 74200, 'nombre' => 'ACTIVIDADES DE FOTOGRAFÍA',                                                                   'categoria' => 'M', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 74900, 'nombre' => 'OTRAS ACTIVIDADES PROFESIONALES, CIENTÍFICAS Y TÉCNICAS N.C.P.',                              'categoria' => 'M', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 75000, 'nombre' => 'ACTIVIDADES VETERINARIAS',                                                                    'categoria' => 'M', 'afecto_iva' => true,  'activo' => true],

            // SECCIÓN N — ACTIVIDADES DE SERVICIOS ADMINISTRATIVOS Y DE APOYO
            ['codigo' => 77100, 'nombre' => 'ALQUILER Y ARRENDAMIENTO DE VEHÍCULOS AUTOMOTORES',                                           'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 77210, 'nombre' => 'ALQUILER Y ARRENDAMIENTO DE EQUIPO RECREATIVO Y DEPORTIVO',                                   'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 77220, 'nombre' => 'ALQUILER DE CINTAS DE VÍDEO Y DISCOS',                                                        'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 77290, 'nombre' => 'ALQUILER Y ARRENDAMIENTO DE OTROS EFECTOS PERSONALES Y ENSERES DOMÉSTICOS',                   'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 77300, 'nombre' => 'ALQUILER Y ARRENDAMIENTO DE OTRA MAQUINARIA, EQUIPO Y BIENES TANGIBLES',                      'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 77400, 'nombre' => 'ARRENDAMIENTO DE PROPIEDAD INTELECTUAL Y PRODUCTOS SIMILARES, EXCEPTO OBRAS PROTEGIDAS POR DERECHOS DE AUTOR', 'categoria' => 'N', 'afecto_iva' => true, 'activo' => true],
            ['codigo' => 78100, 'nombre' => 'ACTIVIDADES DE AGENCIAS DE EMPLEO',                                                           'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 78200, 'nombre' => 'ACTIVIDADES DE AGENCIAS DE EMPLEO TEMPORAL',                                                  'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 78300, 'nombre' => 'OTRAS ACTIVIDADES DE DOTACIÓN DE RECURSOS HUMANOS',                                           'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 79110, 'nombre' => 'ACTIVIDADES DE AGENCIAS DE VIAJES',                                                           'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 79120, 'nombre' => 'ACTIVIDADES DE OPERADORES TURÍSTICOS',                                                        'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 79900, 'nombre' => 'OTROS SERVICIOS DE RESERVAS Y ACTIVIDADES CONEXAS',                                           'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 80100, 'nombre' => 'ACTIVIDADES DE SEGURIDAD PRIVADA',                                                            'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 80200, 'nombre' => 'ACTIVIDADES DE SISTEMAS DE SEGURIDAD',                                                        'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 80300, 'nombre' => 'ACTIVIDADES DE INVESTIGACIÓN',                                                                'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 81100, 'nombre' => 'ACTIVIDADES COMBINADAS DE APOYO A EDIFICIOS',                                                 'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 81210, 'nombre' => 'LIMPIEZA GENERAL DE EDIFICIOS',                                                               'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 81220, 'nombre' => 'OTRAS ACTIVIDADES DE LIMPIEZA DE EDIFICIOS E INSTALACIONES INDUSTRIALES',                     'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 81290, 'nombre' => 'OTRAS ACTIVIDADES DE LIMPIEZA',                                                               'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 81300, 'nombre' => 'ACTIVIDADES DE PAISAJISMO Y SERVICIOS DE MANTENIMIENTO CONEXOS',                              'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 82110, 'nombre' => 'ACTIVIDADES COMBINADAS DE SERVICIOS ADMINISTRATIVOS DE OFICINA',                              'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 82190, 'nombre' => 'FOTOCOPIADO, PREPARACIÓN DE DOCUMENTOS Y OTRAS ACTIVIDADES ESPECIALIZADAS DE APOYO DE OFICINA', 'categoria' => 'N', 'afecto_iva' => true, 'activo' => true],
            ['codigo' => 82200, 'nombre' => 'ACTIVIDADES DE CENTROS DE LLAMADAS',                                                          'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 82300, 'nombre' => 'ORGANIZACIÓN DE CONVENCIONES Y EXPOSICIONES COMERCIALES',                                     'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 82910, 'nombre' => 'ACTIVIDADES DE AGENCIAS DE COBRO Y AGENCIAS DE CALIFICACIÓN CREDITICIA',                      'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 82920, 'nombre' => 'ACTIVIDADES DE ENVASADO Y EMPAQUETADO',                                                       'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 82990, 'nombre' => 'OTRAS ACTIVIDADES DE SERVICIOS DE APOYO A LAS EMPRESAS N.C.P.',                               'categoria' => 'N', 'afecto_iva' => true,  'activo' => true],

            // SECCIÓN O — ADMINISTRACIÓN PÚBLICA
            ['codigo' => 84110, 'nombre' => 'ACTIVIDADES DE LA ADMINISTRACIÓN PÚBLICA EN GENERAL',                                         'categoria' => 'O', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 84120, 'nombre' => 'REGULACIÓN DE LAS ACTIVIDADES DE ORGANISMOS QUE PRESTAN SERVICIOS SANITARIOS, EDUCATIVOS, CULTURALES Y OTROS SERVICIOS SOCIALES', 'categoria' => 'O', 'afecto_iva' => true, 'activo' => true],
            ['codigo' => 84130, 'nombre' => 'REGULACIÓN Y FACILITACIÓN DE LA ACTIVIDAD ECONÓMICA',                                         'categoria' => 'O', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 84210, 'nombre' => 'RELACIONES EXTERIORES',                                                                       'categoria' => 'O', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 84220, 'nombre' => 'ACTIVIDADES DE DEFENSA',                                                                      'categoria' => 'O', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 84230, 'nombre' => 'ACTIVIDADES DE MANTENIMIENTO DEL ORDEN PÚBLICO Y DE SEGURIDAD',                               'categoria' => 'O', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 84240, 'nombre' => 'ACTIVIDADES DE LOS CUERPOS DE BOMBEROS',                                                      'categoria' => 'O', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 84250, 'nombre' => 'ACTIVIDADES DE JUSTICIA Y DE LOS TRIBUNALES',                                                 'categoria' => 'O', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 84300, 'nombre' => 'ACTIVIDADES DE LOS PLANES DE SEGURIDAD SOCIAL DE AFILIACIÓN OBLIGATORIA',                     'categoria' => 'O', 'afecto_iva' => true,  'activo' => true],

            // SECCIÓN P — ENSEÑANZA
            ['codigo' => 85100, 'nombre' => 'ENSEÑANZA PREESCOLAR',                                                                        'categoria' => 'P', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 85200, 'nombre' => 'ENSEÑANZA PRIMARIA',                                                                          'categoria' => 'P', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 85310, 'nombre' => 'ENSEÑANZA SECUNDARIA DE FORMACIÓN GENERAL',                                                   'categoria' => 'P', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 85320, 'nombre' => 'ENSEÑANZA SECUNDARIA DE FORMACIÓN TÉCNICA Y PROFESIONAL',                                     'categoria' => 'P', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 85410, 'nombre' => 'ENSEÑANZA POST-SECUNDARIA NO TERCIARIA DE FORMACIÓN TÉCNICA Y PROFESIONAL',                   'categoria' => 'P', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 85420, 'nombre' => 'ENSEÑANZA TERCIARIA',                                                                         'categoria' => 'P', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 85491, 'nombre' => 'OTROS TIPOS DE ENSEÑANZA',                                                                    'categoria' => 'P', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 85499, 'nombre' => 'OTROS TIPOS DE ENSEÑANZA N.C.P.',                                                             'categoria' => 'P', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 85500, 'nombre' => 'ACTIVIDADES DE APOYO A LA ENSEÑANZA',                                                         'categoria' => 'P', 'afecto_iva' => false, 'activo' => true],

            // SECCIÓN Q — ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA Y DE ASISTENCIA SOCIAL
            ['codigo' => 86100, 'nombre' => 'ACTIVIDADES DE HOSPITALES',                                                                   'categoria' => 'Q', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 86200, 'nombre' => 'ACTIVIDADES DE MÉDICOS Y ODONTÓLOGOS',                                                        'categoria' => 'Q', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 86901, 'nombre' => 'LABORATORIOS CLÍNICOS',                                                                       'categoria' => 'Q', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 86902, 'nombre' => 'SERVICIOS DE IMAGENOLOGÍA',                                                                   'categoria' => 'Q', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 86903, 'nombre' => 'SERVICIOS DE AMBULANCIAS',                                                                    'categoria' => 'Q', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 86909, 'nombre' => 'OTRAS ACTIVIDADES DE ATENCIÓN DE LA SALUD HUMANA N.C.P.',                                     'categoria' => 'Q', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 87100, 'nombre' => 'ACTIVIDADES DE ATENCIÓN DE ENFERMERÍA EN ESTABLECIMIENTOS ESPECIALIZADOS',                    'categoria' => 'Q', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 87200, 'nombre' => 'ACTIVIDADES DE ATENCIÓN EN ESTABLECIMIENTOS DE PERSONAS CON DISCAPACIDAD MENTAL Y DEPENDIENTES DE SUSTANCIAS PSICOACTIVAS', 'categoria' => 'Q', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 87300, 'nombre' => 'ACTIVIDADES DE ATENCIÓN EN ESTABLECIMIENTOS DE ANCIANOS Y PERSONAS CON DISCAPACIDAD',         'categoria' => 'Q', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 87900, 'nombre' => 'OTRAS ACTIVIDADES DE ATENCIÓN EN INSTITUCIONES',                                              'categoria' => 'Q', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 88100, 'nombre' => 'ACTIVIDADES DE ASISTENCIA SOCIAL SIN ALOJAMIENTO PARA PERSONAS MAYORES Y CON DISCAPACIDAD',   'categoria' => 'Q', 'afecto_iva' => false, 'activo' => true],
            ['codigo' => 88900, 'nombre' => 'OTRAS ACTIVIDADES DE ASISTENCIA SOCIAL SIN ALOJAMIENTO',                                     'categoria' => 'Q', 'afecto_iva' => false, 'activo' => true],

            // SECCIÓN R — ARTES, ENTRETENIMIENTO Y RECREACIÓN
            ['codigo' => 90000, 'nombre' => 'ACTIVIDADES CREATIVAS, ARTÍSTICAS Y DE ENTRETENIMIENTO',                                      'categoria' => 'R', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 91010, 'nombre' => 'ACTIVIDADES DE BIBLIOTECAS Y ARCHIVOS',                                                       'categoria' => 'R', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 91020, 'nombre' => 'ACTIVIDADES DE MUSEOS Y GESTIÓN DE LUGARES Y EDIFICIOS HISTÓRICOS',                           'categoria' => 'R', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 91030, 'nombre' => 'ACTIVIDADES DE JARDINES BOTÁNICOS, ZOOLÓGICOS Y RESERVAS NATURALES',                          'categoria' => 'R', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 92000, 'nombre' => 'ACTIVIDADES DE JUEGOS DE AZAR Y APUESTAS',                                                    'categoria' => 'R', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 93110, 'nombre' => 'GESTIÓN DE INSTALACIONES DEPORTIVAS',                                                         'categoria' => 'R', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 93120, 'nombre' => 'ACTIVIDADES DE CLUBES DEPORTIVOS',                                                            'categoria' => 'R', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 93130, 'nombre' => 'ACTIVIDADES DE GIMNASIOS',                                                                    'categoria' => 'R', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 93190, 'nombre' => 'OTRAS ACTIVIDADES DEPORTIVAS',                                                                'categoria' => 'R', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 93210, 'nombre' => 'ACTIVIDADES DE PARQUES DE ATRACCIONES Y PARQUES TEMÁTICOS',                                   'categoria' => 'R', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 93290, 'nombre' => 'OTRAS ACTIVIDADES DE ESPARCIMIENTO Y RECREACIÓN N.C.P.',                                      'categoria' => 'R', 'afecto_iva' => true,  'activo' => true],

            // SECCIÓN S — OTRAS ACTIVIDADES DE SERVICIOS
            ['codigo' => 94110, 'nombre' => 'ACTIVIDADES DE ASOCIACIONES EMPRESARIALES Y DE EMPLEADORES',                                  'categoria' => 'S', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 94120, 'nombre' => 'ACTIVIDADES DE ASOCIACIONES PROFESIONALES',                                                   'categoria' => 'S', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 94200, 'nombre' => 'ACTIVIDADES DE SINDICATOS',                                                                   'categoria' => 'S', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 94910, 'nombre' => 'ACTIVIDADES DE ORGANIZACIONES RELIGIOSAS',                                                    'categoria' => 'S', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 94920, 'nombre' => 'ACTIVIDADES DE ORGANIZACIONES POLÍTICAS',                                                     'categoria' => 'S', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 94990, 'nombre' => 'ACTIVIDADES DE OTRAS ASOCIACIONES N.C.P.',                                                    'categoria' => 'S', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 95110, 'nombre' => 'REPARACIÓN DE COMPUTADORES Y EQUIPO PERIFÉRICO',                                              'categoria' => 'S', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 95120, 'nombre' => 'REPARACIÓN DE EQUIPO DE COMUNICACIONES',                                                      'categoria' => 'S', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 95210, 'nombre' => 'REPARACIÓN DE APARATOS ELECTRÓNICOS DE CONSUMO',                                              'categoria' => 'S', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 95220, 'nombre' => 'REPARACIÓN DE APARATOS DOMÉSTICOS Y EQUIPO DOMÉSTICO Y DE JARDINERÍA',                        'categoria' => 'S', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 95230, 'nombre' => 'REPARACIÓN DE CALZADO Y ARTÍCULOS DE CUERO',                                                  'categoria' => 'S', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 95240, 'nombre' => 'REPARACIÓN DE MUEBLES Y ARTÍCULOS PARA EL HOGAR',                                             'categoria' => 'S', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 95290, 'nombre' => 'REPARACIÓN DE OTROS EFECTOS PERSONALES Y ENSERES DOMÉSTICOS',                                 'categoria' => 'S', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 96010, 'nombre' => 'LAVADO Y LIMPIEZA DE PRENDAS DE VESTIR',                                                      'categoria' => 'S', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 96020, 'nombre' => 'PELUQUERÍA Y OTROS TRATAMIENTOS DE BELLEZA',                                                  'categoria' => 'S', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 96030, 'nombre' => 'POMPAS FÚNEBRES Y ACTIVIDADES CONEXAS',                                                       'categoria' => 'S', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 96040, 'nombre' => 'ACTIVIDADES DE MANTENIMIENTO FÍSICO',                                                         'categoria' => 'S', 'afecto_iva' => true,  'activo' => true],
            ['codigo' => 96090, 'nombre' => 'OTRAS ACTIVIDADES DE SERVICIOS PERSONALES N.C.P.',                                            'categoria' => 'S', 'afecto_iva' => true,  'activo' => true],

            // SECCIÓN T — ACTIVIDADES DE HOGARES COMO EMPLEADORES
            ['codigo' => 97000, 'nombre' => 'ACTIVIDADES DE HOGARES COMO EMPLEADORES DE PERSONAL DOMÉSTICO',                               'categoria' => 'T', 'afecto_iva' => true,  'activo' => true],

            // SECCIÓN U — ACTIVIDADES DE ORGANIZACIONES EXTRATERRITORIALES
            ['codigo' => 99000, 'nombre' => 'ACTIVIDADES DE ORGANIZACIONES Y ÓRGANOS EXTRATERRITORIALES',                                  'categoria' => 'U', 'afecto_iva' => true,  'activo' => true],
        ];

        foreach (array_chunk($actividades, 50) as $chunk) {
            DB::table('sii_cat_acteco')->insertOrIgnore($chunk);
        }
    }
}
